(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib._300x600_mask = function() {
	this.initialize(img._300x600_mask);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.rainMan = function() {
	this.initialize(img.rainMan);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,287);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.m_subheadshape = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D70891").s().p("A3WDrIAApDMAutgAeIhaLtg");
	this.shape.setTransform(129.5,37.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_subheadshape, new cjs.Rectangle(-20,0,299,75), null);


(lib.m_subhead = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAdAmIAAgxQgBgGgBgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAgBAAQgDAAgDACIgFAHIAAAyIgVAAIAAgxQAAgGgCgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAAAAAQgEAAgDACIgFAHIAAAyIgWAAIAAhJIATAAIACAJQAEgGAFgDQAGgCAHAAQAGAAAEADQAEADACAFQAEgGAGgDQAGgCAGAAQAEAAAEABQAEACADACIADAHQACAFAAAFIAAA1g");
	this.shape.setTransform(232.8,30.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAlQgHgDgFgFQgEgFgDgIQgBgFgBgLQAAgIACgHQADgIAEgFQAFgFAHgDQAEgBAKgCQAJABAGACQAHADAFAEQAFAGACAHQACALAAAFQAAAJgCAHQgCAHgFAGQgFAFgHADQgJADgGAAQgHAAgHgDgAgFgVIgEAEQgCADAAAEIgBAKIABALQAAAEACACQACAEACABIAFABIAGgBQADgBABgEIADgGIABgLIgBgKIgDgHQgBgDgDgBQgCgCgEABQgCgBgDACg");
	this.shape_1.setTransform(222.8,31.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgJAlQgGgDgFgFQgFgGgDgHQgCgHAAgIQAAgIACgIQADgHAFgGQAFgFAGgDIAIgCIAHgBQAHAAAGACQAHADAFAEIgKAOIgGgFIgIgBIgGABIgEAFIgDAGIgBALIABAKIAEAGIADAEIAGABQAEAAADgBIAHgFIAKAPQgFAEgHACQgGACgHABQgKgBgFgCg");
	this.shape_2.setTransform(215.7,31.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgIAJQgEgEAAgFQAAgEAEgEQAEgEAEAAQAFAAAEAEQAEAEAAAEQAAAFgEAEQgEAEgFAAQgEAAgEgEg");
	this.shape_3.setTransform(210.6,33.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDAuQgEgCgDgDQgDgEgCgFQgBgFAAgGIAAgiIgKAAIAAgPIAKAAIAAgQIAVgDIAAATIARAAIgDAPIgOAAIAAAiQAAAFACACQABACAEAAQAEAAAEgCIAIAOQgEADgGABQgFACgGAAQgGAAgEgCg");
	this.shape_4.setTransform(206.4,30.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAKAmIAAgxQAAgGgCgCQgCgCgDAAQgDAAgDACIgGAHIAAAyIgWAAIAAhJIATAAIACAJQAFgGAFgDQAFgCAGAAQAFAAAEABIAHAEIAEAHQABAFAAAFIAAA1g");
	this.shape_5.setTransform(199.7,30.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgFAnIgIgCIgGgEIgFgEQgFgGgCgHQgDgHABgJQgBgIADgGQACgIAFgFQAEgGAGgDIAHgCIAHgBQAIABAGACQAHADAFAEQAEAFACAHQADAIAAAIIgBAHIgtAAIACAIIAEAGIAFACIAFABQAEAAAEgBQAFgCAEgEIAKANQgGAFgHADQgKADgGAAgAgDgXIgEADIgCAGIgCAIIAYAAIAAgBQAAgIgDgFIgEgDIgFgBIgEABg");
	this.shape_6.setTransform(191.9,31.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AANAwIgTglIgJAAIAAAlIgXAAIAAhgIAgAAQAJAAAHADQAHABAGADQAEAEAEAGQACAGAAAHQAAAFgBAEQgBAEgDADIgFAEIgJAFIAZApgAgPgEIAKAAIAFAAQAEgBABgCQACgBABgEIABgGIgBgGIgDgEQgCgCgDgBIgHgBIgIAAg");
	this.shape_7.setTransform(184.3,29.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgXAmIAAhJIATAAIADAOIACgHIAEgFIAFgDIAHgBIAHABIgEAVIgHgBIgFABQgDACgCACQgCACAAAEIgBAGIAAAlg");
	this.shape_8.setTransform(177.3,30.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAlQgHgDgFgFQgEgFgDgIQgBgFgBgLQAAgIACgHQADgIAEgFQAFgFAHgDQAEgBAKgCQAJABAGACQAHADAFAEQAFAGACAHQACALAAAFQAAAJgCAHQgCAHgFAGQgFAFgHADQgJADgGAAQgHAAgHgDgAgFgVIgEAEQgCADAAAEIgBAKIABALQAAAEACACQACAEACABIAFABIAGgBQADgBABgEIADgGIABgLIgBgKIgDgHQgBgDgDgBQgCgCgEABQgCgBgDACg");
	this.shape_9.setTransform(170,31.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgcAwIAAhgIA5AAIgDARIgfAAIAAAaIAcAAIAAAPIgcAAIAAAmg");
	this.shape_10.setTransform(163.1,29.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAPAmIAAgyIAAgHIgDgFQgDgDgGAAQgFAAgEAEQgFADgEAGIAAA0IgMAAIAAhJIALAAIABALQAEgGAFgDIAGgDIAHgBQAEAAAFACQADABAEADIADAHQACAFAAAFIAAA0g");
	this.shape_11.setTransform(151.7,31);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNAkQgGgCgFgGQgEgFgCgHQgCgHAAgJQAAgIACgGQACgIAEgFQAFgFAGgCQAGgEAHAAQAIAAAGAEQAGACAFAFQADAFACAHQADAHAAAIQAAAJgDAGQgBAIgFAFQgEAFgGADQgGACgIABQgHgBgGgCgAgHgZQgEABgCAEQgCAEgCAEIgBAMIABANIADAJQADADADABQAEADAEAAQAEAAAEgDQAEgBACgDQACgEABgFQACgFAAgIQAAgGgCgGQgBgEgCgEQgCgEgEgBQgEgCgEAAQgEAAgDACg");
	this.shape_12.setTransform(143.6,31.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIAmIgIgCQgHgCgEgFIAHgIQAEAEAFABQAFADAGAAQAHAAADgEQAFgCAAgGIgBgEQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQgDgDgKgDIgKgDQgEgBgDgDQgDgDgBgDQgBgDgBgFQABgEACgDQACgEADgCQAEgDAFgCQAFgBAEgBQAIAAAGACQAGADAGAEIgGAIQgFgDgFgBQgEgCgFAAQgGAAgDADQgEACAAAEQAAAFADACQAEADAIADIALACIAHAFQADACACAEQACADgBAFQABAGgDAEQgCAEgFADQgDADgGACIgKABg");
	this.shape_13.setTransform(132.7,31.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAAAuIgFgEIgEgHQgCgEAAgFIAAgsIgNAAIAAgKIANAAIAAgQIAMgCIAAASIASAAIgCAKIgQAAIAAArQAAAGACADQACACAFAAQAFAAAFgDIAFAJIgIAEIgJABIgIgBg");
	this.shape_14.setTransform(127.1,30.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAPAmIAAgyIgBgHIgCgFQgDgDgFAAQgFAAgFAEQgEADgEAGIAAA0IgNAAIAAhJIALAAIABALQAEgGAGgDIAFgDIAGgBQAGAAADACQAFABACADIAEAHQACAFAAAFIAAA0g");
	this.shape_15.setTransform(120.6,31);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLAkQgGgCgEgFQgEgGgCgHQgDgGAAgJQAAgIADgHQACgHADgGQAFgEAFgDQAGgEAGAAQAHABAGACQAGACAEAFQAEAFACAHQABAGAAAJIAAAGIguAAQAAAGACAEQACAFADADIAFAEIAHABQAFAAAFgCIAJgEIAGAIQgGAEgGACQgGACgIABQgGgBgHgCgAgFgaQgDACgDACQgCADgBAFIgCAKIAiAAIAAgBQAAgFgBgEIgEgIQgCgCgDgCIgHgBIgGABg");
	this.shape_16.setTransform(112.7,31.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAiAmIAAgyIgBgHIgCgFQgDgDgFAAQgFAAgEAEQgDADgFAGIAAA0IgLAAIAAgyIgBgHIgDgFQgCgDgFAAQgGAAgEAEIgHAJIAAA0IgNAAIAAhJIALAAIABALQAEgGAFgDIAFgDIAHgBIAHABIAFADIADAEIADAGQAEgHAFgDIAGgDIAHgBQAEAAAEACQAEABACADIAFAHQABAFAAAFIAAA0g");
	this.shape_17.setTransform(103.1,31);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAAuIgFgEIgEgHQgCgEAAgFIAAgsIgNAAIAAgKIANAAIAAgQIAMgCIAAASIASAAIgCAKIgQAAIAAArQAAAGACADQACACAFAAQAFAAAFgDIAFAJIgIAEIgJABIgIgBg");
	this.shape_18.setTransform(94.6,30.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSAmIAAhJIAKAAIABAPIAEgHIADgGIAGgDIAGgBIAHABIgCANIgGgBQgDAAgDABIgFAEIgDAGIgDAKIAAApg");
	this.shape_19.setTransform(90.1,31);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AATAjQgDgCgCgFQgEAFgGADQgEACgHABQgFgBgFgBQgEgCgDgDQgDgCgCgFQgBgDAAgGQAAgFACgFQACgEAEgDQAEgDAGgBQAGgCAHAAIALAAIAAgGIgBgGIgCgEQgCgCgDgBIgGgBIgJABIgLADIgDgJIANgEIAMgCQAGABAFABQAFACADADQADADACAFQABAEAAAGIAAAhQAAAFACABIAEAEIgDAJQgFgBgEgDgAgFACQgEABgDACQgCABgBADQgCADAAADQAAAHADADQAEAEAGAAQAFAAAEgDQAEgCADgHIAAgQIgJAAIgIABg");
	this.shape_20.setTransform(83,31.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgegyIAMAAIABAKQAEgGAFgDQAGgDAFAAQAHAAAGADQAFADADAFQADAFACAHQACAHgBAJQAAAIgCAGQgBAHgEAGQgEAFgFADQgGACgHAAQgEAAgFgCQgFgCgEgEIAAAjIgNACgAgJgmQgEADgEAFIAAAjQADAEAEADQAEACAGAAQADAAADgCQADgBADgEIAEgIIABgMIgBgNQgCgFgCgEQgCgDgDgCQgDgBgEAAQgEAAgFADg");
	this.shape_21.setTransform(75.5,32.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AATAjQgDgCgCgFQgEAFgGADQgEACgHABQgFgBgFgBQgEgCgDgDQgDgCgCgFQgBgDAAgGQAAgFACgFQACgEAEgDQAEgDAGgBQAGgCAHAAIALAAIAAgGIgBgGIgCgEQgCgCgDgBIgGgBIgJABIgLADIgDgJIANgEIAMgCQAGABAFABQAFACADADQADADACAFQABAEAAAGIAAAhQAAAFACABIAEAEIgDAJQgFgBgEgDgAgFACQgEABgDACQgCABgBADQgCADAAADQAAAHADADQAEAEAGAAQAFAAAEgDQAEgCADgHIAAgQIgJAAIgIABg");
	this.shape_22.setTransform(67.3,31.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgOAzQgFgDgEgFQgDgFgCgHQgCgHAAgJQAAgIACgHQACgHAEgFQADgFAGgDQAGgDAGAAQAGAAAFADIAIAGIAAgmIANABIAABnIgMAAIAAgLQgEAGgFADQgGADgGAAQgGAAgGgCgAgGgLQgDACgCAEQgCADgCAEQgBAGAAAHIABANQABAFACADQADAEACABQAEACADAAQAGAAAEgDQAEgCAEgGIAAgjQgEgFgDgCQgFgCgFAAQgDAAgEABg");
	this.shape_23.setTransform(55.7,29.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgLAkQgFgCgFgFQgEgGgDgHQgBgGAAgJQAAgIABgHQACgHAFgGQADgEAHgDQAFgEAGAAQAHABAGACQAGACAEAFQAEAFABAHQADAGAAAJIAAAGIgvAAQABAGACAEQABAFACADIAHAEIAGABQAGAAAEgCIAKgEIAFAIQgGAEgGACQgGACgIABQgHgBgGgCgAgFgaQgDACgDACQgCADgBAFIgCAKIAiAAIAAgBQAAgFgCgEIgCgIQgCgCgEgCIgIgBIgFABg");
	this.shape_24.setTransform(48,31.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgRA3QgGgCgEgDQgEgDgBgEQgCgEAAgGIAMAAIABAGIADADQACADAEAAIAKABIAJgBIAHgCQACgBABgDIABgEQAAgGgDgCQgEgEgHAAIgLAAIgJgBQgDgBgCgBIgEgFQgBgCAAgDQAAgEACgDQACgDAEgDQgGgCgDgGQgDgEAAgIQAAgFACgFQACgFAEgDQAEgDAFgDQAFgCAGAAIAUgBIANgFIAEAMIgKABIgMABQAHADADAFQADAEAAAGQAAAGgCAEQgCAFgDADQgEAEgFABQgGACgFAAQgFgBgFgBQgDADAAAEQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAQACACAFAAIALAAQAGAAAFABQAEACAEADIAFAGQABAEAAAEQAAAGgCAEQgCAEgEADQgFADgGACQgHABgHAAQgJAAgGgBgAgJgmIgEAEIgDAEIgBAHIABAHIADAFIAFAEIAGABIAGgBIAFgEIADgEIABgIIgBgHIgDgFIgFgDIgGgBIgHABg");
	this.shape_25.setTransform(40.8,32.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AATAjQgDgCgCgFQgEAFgGADQgEACgHABQgFgBgFgBQgEgCgDgDQgDgCgCgFQgBgDAAgGQAAgFACgFQACgEAEgDQAEgDAGgBQAGgCAHAAIALAAIAAgGIgBgGIgCgEQgCgCgDgBIgGgBIgJABIgLADIgDgJIANgEIAMgCQAGABAFABQAFACADADQADADACAFQABAEAAAGIAAAhQAAAFACABIAEAEIgDAJQgFgBgEgDgAgFACQgEABgDACQgCABgBADQgCADAAADQAAAHADADQAEAEAGAAQAFAAAEgDQAEgCADgHIAAgQIgJAAIgIABg");
	this.shape_26.setTransform(33.2,31.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAPAmIAAgyIgBgHIgCgFQgDgDgGAAQgEAAgFAEQgFADgEAGIAAA0IgMAAIAAhJIALAAIABALQAEgGAFgDIAGgDIAHgBQAEAAAFACQADABADADIAFAHQABAFAAAFIAAA0g");
	this.shape_27.setTransform(25.5,31);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AATAjQgDgCgCgFQgEAFgGADQgEACgHABQgFgBgFgBQgEgCgDgDQgDgCgCgFQgBgDAAgGQAAgFACgFQACgEAEgDQAEgDAGgBQAGgCAHAAIALAAIAAgGIgBgGIgCgEQgCgCgDgBIgGgBIgJABIgLADIgDgJIANgEIAMgCQAGABAFABQAFACADADQADADACAFQABAEAAAGIAAAhQAAAFACABIAEAEIgDAJQgFgBgEgDgAgFACQgEABgDACQgCABgBADQgCADAAADQAAAHADADQAEAEAGAAQAFAAAEgDQAEgCADgHIAAgQIgJAAIgIABg");
	this.shape_28.setTransform(17.6,31.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAiAmIAAgyIgBgHIgCgFQgCgDgFAAQgGAAgEAEQgDADgEAGIAAA0IgNAAIAAgyIgBgHIgBgFQgDgDgFAAQgFAAgFAEIgIAJIAAA0IgMAAIAAhJIALAAIABALQAEgGAFgDIAGgDIAGgBIAGABIAGADIADAEIADAGQAEgHAFgDIAGgDIAHgBQAFAAADACQAEABADADIADAHQACAFAAAFIAAA0g");
	this.shape_29.setTransform(8.1,31);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAPA0IAAgzIgBgGIgCgEQgDgDgFAAQgFAAgFADQgFAEgDAFIAAA0IgNAAIAAhmIANgBIAAApQAEgGAFgDQAFgDAGAAQAGAAADABQAFACACADIAFAHQABAEAAAFIAAA0g");
	this.shape_30.setTransform(206.7,11.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAAAuIgFgEIgEgHQgCgEAAgFIAAgsIgNAAIAAgKIANAAIAAgQIAMgCIAAASIASAAIgCAKIgQAAIAAArQAAAGACADQACACAFAAQAFAAAFgDIAFAJIgIAEIgJABIgIgBg");
	this.shape_31.setTransform(200.1,12.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgFA3IAAhJIAMAAIAABJgAgGgnQgCgCAAgEQAAgDACgDQADgCADAAQAEAAADACQACADAAADQAAAEgCACQgDADgEAAQgDAAgDgDg");
	this.shape_32.setTransform(195.7,11.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AANAlIgNg9IgMA9IgRAAIgRhJIAMAAIAOBAIAOhAIAOAAIAOBAIANhAIAMAAIgQBJg");
	this.shape_33.setTransform(188.9,13.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgLAkQgFgDgFgFQgEgEgDgIQgCgHAAgIQAAgHACgIQADgHADgGQAEgFAGgDQAGgCAGAAQAIgBAFADQAGADAEAEQAEAFACAGQACAIAAAIIAAAGIgvAAQAAAGADAFQABAEACADIAGAEIAHABQAFAAAFgCIAJgEIAGAHQgGAFgGACQgHACgHAAQgGAAgHgCgAgFgaQgEABgCAEQgCACgBAEIgCALIAiAAIAAgBQAAgFgCgFIgDgGQgCgEgDgBIgHgBIgGABg");
	this.shape_34.setTransform(176.5,13.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgHAlIgZhJIAOAAIASA+IATg+IAOAAIgZBJg");
	this.shape_35.setTransform(169.4,13.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgTAmIAAhJIAMAAIABAPIADgHIAEgGIAFgDIAGgBIAIABIgDANIgGgBQgEAAgDABIgEAEIgDAGIgDAKIAAApg");
	this.shape_36.setTransform(163.9,13.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgLAkQgFgDgFgFQgEgEgDgIQgBgHAAgIQAAgHABgIQACgHAFgGQADgFAHgDQAFgCAGAAQAHgBAGADQAGADAEAEQAEAFABAGQADAIAAAIIAAAGIgvAAQABAGACAFQABAEACADIAHAEIAGABQAGAAAEgCIAKgEIAFAHQgGAFgGACQgGACgIAAQgHAAgGgCgAgFgaQgDABgDAEQgCACgBAEIgCALIAiAAIAAgBQAAgFgCgFIgCgGQgCgEgEgBIgIgBIgFABg");
	this.shape_37.setTransform(156.9,13.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgIAmIgIgCQgHgDgEgEIAHgIQAEADAFACQAFACAGAAQAHAAADgCQAFgEAAgFIgBgEQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQgDgDgKgDIgKgDQgFgCgCgCQgDgDgBgDQgBgEgBgEQABgDACgFQACgDAEgCQADgEAFgBQAFgCAEABQAIAAAGABQAGADAGAEIgGAJQgFgEgFgCQgEgBgFAAQgGAAgDACQgEADAAAEQAAAFADADQAEACAIACIALAEIAHADQADADACAEQACAEgBAEQABAGgDAEQgCAEgFADQgDADgGABIgKABg");
	this.shape_38.setTransform(149.8,13.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgLAkQgGgDgEgFQgEgEgCgIQgDgHAAgIQAAgHADgIQACgHADgGQAFgFAFgDQAGgCAGAAQAHgBAGADQAGADAEAEQAEAFACAGQABAIAAAIIAAAGIguAAQAAAGACAFQACAEADADIAFAEIAHABQAFAAAFgCIAJgEIAGAHQgGAFgGACQgGACgIAAQgGAAgHgCgAgFgaQgDABgDAEQgCACgBAEIgCALIAiAAIAAgBQAAgFgBgFIgEgGQgCgEgDgBIgHgBIgGABg");
	this.shape_39.setTransform(142.9,13.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgOAzQgFgDgDgFQgEgFgCgHQgCgHAAgJQAAgIACgHQACgHAEgFQADgFAGgDQAGgDAGAAQAGAAAEADQAFACAEAEIAAgmIANABIAABnIgMAAIgBgLQgDAGgGADQgFADgGAAQgHAAgFgCgAgGgLQgDACgCAEQgCADgCAEQgBAGAAAHIABANQABAFADADQABAEADABQAEACADAAQAFAAAFgDQAEgCAEgGIAAgjQgEgFgEgCQgEgCgFAAQgDAAgEABg");
	this.shape_40.setTransform(134.7,11.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgPAkQgEgBgCgDQgDgDgBgEQgCgEAAgGIAAg0IANAAIAAAzQAAAHADAEQADADAGAAQAEAAAFgEQAEgDAEgGIAAg0IANAAIAABJIgLAAIgBgLIgFAGIgFAEIgGACIgGABQgFAAgEgCg");
	this.shape_41.setTransform(123.2,13.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgNAkQgGgDgEgFQgFgFgCgHQgCgHAAgJQAAgHACgIQACgHAFgFQAEgFAGgDQAGgCAHAAQAIAAAGACQAGADAEAFQAFAFACAHQACAHAAAIQAAAIgCAIQgCAHgFAFQgEAFgGADQgGACgIAAQgHAAgGgCgAgHgaQgDACgDAEQgDAEgBAFIgBALIABANIAEAJQACADAEABQADACAEAAQAFAAADgCQADgBADgDQACgEABgFQACgGAAgHQAAgGgCgFQgBgFgCgEQgDgEgDgCQgDgBgFAAQgEAAgDABg");
	this.shape_42.setTransform(115.2,13.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgbAqIAKgDIAHgDQADgEAEgKIgFAAIgYhJIANAAIATA/IATg/IAOAAIgZBJIgEAMQgDAFgDADQgEAEgFACQgHADgHABg");
	this.shape_43.setTransform(107.8,14.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgLAkQgFgDgFgFQgEgEgDgIQgBgHAAgIQAAgHABgIQACgHAFgGQADgFAHgDQAFgCAGAAQAHgBAGADQAGADAEAEQAEAFABAGQADAIAAAIIAAAGIgvAAQABAGACAFQABAEACADIAHAEIAGABQAGAAAEgCIAKgEIAFAHQgGAFgGACQgGACgIAAQgHAAgGgCgAgFgaQgDABgDAEQgCACgBAEIgCALIAiAAIAAgBQAAgFgCgFIgCgGQgCgEgEgBIgIgBIgFABg");
	this.shape_44.setTransform(97,13.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgDA0IgFgDIgDgFIgBgHIAAhYIAMgBIAABZIABAEQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIAFgBIADAJQgFACgGAAIgFgBg");
	this.shape_45.setTransform(91.7,11.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgbAqIAKgDIAGgDQAEgEAEgKIgFAAIgYhJIANAAIATA/IAUg/IANAAIgZBJIgEAMQgDAFgDADQgEAEgGACQgFADgIABg");
	this.shape_46.setTransform(85.9,14.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AAAAuIgFgEIgEgHQgCgEAAgFIAAgsIgNAAIAAgKIANAAIAAgQIAMgCIAAASIASAAIgCAKIgQAAIAAArQAAAGACADQACACAFAAQAFAAAFgDIAFAJIgIAEIgJABIgIgBg");
	this.shape_47.setTransform(80,12.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgJAmIgHgCQgGgDgGgEIAHgIQAFADAFACQAFACAGAAQAGAAAFgCQAEgEAAgFIgBgEQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgFgDgJgDIgKgDQgFgCgCgCQgDgDgBgDQgBgEAAgEQAAgDACgFQACgDAEgCQADgEAEgBQAGgCAFABQAHAAAGABQAGADAFAEIgFAJQgFgEgEgCQgFgBgFAAQgGAAgDACQgEADAAAEQAAAFAEADQADACAIACIAKAEIAIADQADADACAEQACAEAAAEQAAAGgDAEQgCAEgEADQgEADgGABIgKABg");
	this.shape_48.setTransform(74.3,13.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgKAkQgGgDgFgFQgEgEgDgIQgBgHAAgIQAAgHABgIQACgHAFgGQADgFAHgDQAFgCAGAAQAHgBAGADQAGADAEAEQAEAFABAGQADAIAAAIIAAAGIgvAAQABAGACAFQABAEACADIAHAEIAGABQAGAAAEgCIAKgEIAFAHQgGAFgGACQgGACgIAAQgHAAgFgCgAgFgaQgDABgCAEQgDACgBAEIgCALIAiAAIAAgBQAAgFgCgFIgCgGQgCgEgEgBIgIgBIgFABg");
	this.shape_49.setTransform(67.3,13.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgNA1IAAg/IgNAAIAAgKIANAAIAAgLQAAgEABgEQACgDADgDQADgDAEgCQAEgBAFgBIAKABIAIAEIgEAJQgGgDgHAAQgGAAgCADQgCACAAAFIAAALIARAAIgCAKIgPAAIAAA/g");
	this.shape_50.setTransform(61.8,11.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgFA3IAAhJIALAAIAABJgAgFgnQgDgCAAgEQAAgDADgDQACgCADAAQAEAAACACQADADAAADQAAAEgDACQgCADgEAAQgDAAgCgDg");
	this.shape_51.setTransform(57.1,11.5);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgDA0IgFgDIgDgFIgBgHIAAhYIAMgBIAABZIABAEQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIAFgBIADAJQgFACgGAAIgFgBg");
	this.shape_52.setTransform(53.6,11.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgLAkQgFgDgFgFQgEgEgDgIQgCgHAAgIQAAgHACgIQADgHADgGQAEgFAGgDQAGgCAGAAQAIgBAFADQAGADAEAEQAEAFACAGQABAIAAAIIAAAGIguAAQAAAGACAFQACAEACADIAGAEIAHABQAFAAAFgCIAJgEIAGAHQgGAFgGACQgHACgHAAQgGAAgHgCgAgFgaQgEABgCAEQgCACgBAEIgCALIAiAAIAAgBQAAgFgCgFIgDgGQgCgEgDgBIgHgBIgGABg");
	this.shape_53.setTransform(43.8,13.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AAPA0IAAgzIgBgGIgCgEQgDgDgGAAQgEAAgFADQgEAEgFAFIAAA0IgMAAIAAhmIAMgBIAAApQAFgGAFgDQAFgDAHAAQAEAAAFABQADACADADIAFAHQABAEAAAFIAAA0g");
	this.shape_54.setTransform(36,11.7);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAAAuIgFgEIgEgHQgCgEAAgFIAAgsIgNAAIAAgKIANAAIAAgQIAMgCIAAASIASAAIgCAKIgQAAIAAArQAAAGACADQACACAFAAQAFAAAFgDIAFAJIgIAEIgJABIgIgBg");
	this.shape_55.setTransform(29.4,12.4);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AAAAuIgFgEIgEgHQgCgEAAgFIAAgsIgNAAIAAgKIANAAIAAgQIAMgCIAAASIASAAIgCAKIgQAAIAAArQAAAGACADQACACAFAAQAFAAAFgDIAFAJIgIAEIgJABIgIgBg");
	this.shape_56.setTransform(20.9,12.4);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgKAkQgGgDgFgFQgEgEgDgIQgBgHAAgIQAAgHABgIQACgHAFgGQADgFAHgDQAFgCAGAAQAHgBAGADQAGADAEAEQADAFACAGQACAIABAIIAAAGIgvAAQAAAGADAFQABAEACADIAHAEIAGABQAFAAAFgCIAKgEIAFAHQgGAFgGACQgHACgHAAQgHAAgFgCgAgFgaQgDABgCAEQgDACgBAEIgCALIAiAAIAAgBQAAgFgCgFIgCgGQgCgEgEgBIgIgBIgFABg");
	this.shape_57.setTransform(14.6,13.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgEAxIgHgCIgHgEIgGgGIgEgHIgEgIIgCgKIgBgMIABgKIACgLIAFgIIAFgHIAGgGIAHgEIAIgCIAHgBQAHAAAJADQAGACAHAGIgIAIIgKgGQgEgCgHAAQgGAAgDACQgFACgEAFQgEAFgCAHQgCALAAAGQAAAKABAIQACAHADAFQADAFAFACQAFACAGAAQAFAAAEgBIAJgDIAAgdIgRAAIgBgKIAfAAIAAAtQgHAFgIACQgKACgIAAg");
	this.shape_58.setTransform(6.4,12.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_subhead, new cjs.Rectangle(0,0,248,41.7), null);


(lib.m_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBoQgWgIgQgOQgPgPgKgUQgJgWAAgZQAAgZAJgUQAKgVAPgOQAQgQAWgHQATgIAXAAQAXAAAUAIQAWAHAPAQQAQAOAJAVQAKAUAAAZQAAAagKAVQgJAUgQAPQgPAOgWAIQgUAIgXAAQgXAAgTgIgAgghQQgQAGgLAMQgLALgHARQgGAQgBASQABAUAGAPQAHAQALANQAMAMAPAGQAQAGAQABQAQgBARgGQAOgGANgMQALgMAHgRQAGgPABgUQgBgSgGgQQgHgRgLgLQgLgMgQgGQgPgHgSAAQgSAAgOAHgAAaA/Igdg2IgQAAIAAA2IgZAAIAAh9IAvAAQAXAAANAIQANAJAAAUQAAAJgCAGQgEAHgEADQgEADgGACIgNADIAhA3gAgTgJIAWAAQAKgBAHgDQAHgCAAgMQAAgFgDgDIgGgFIgIgCIgJAAIgUAAg");
	this.shape.setTransform(245.7,25.6,0.374,0.373);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiyDIQg8hPAAh9QAAh5BChQQBHhUB1AAQBVAAA6AlQA+AnASBKIgpAAQgQg3gygfQgwgdhEAAQhiAAg8BOQg2BGAABmQAAB0A1BFQA4BJBnAAQA6AAAugcQAsgcAYgwIAsAAQgbBDg6AlQg5AkhKAAQh+AAhEhag");
	this.shape_1.setTransform(180.6,38.8,0.374,0.373);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgsAtQgTgSAAgbQAAgaATgSQASgTAaAAQAaAAAUATQASASAAAaQAAAbgSASQgUATgaAAQgaAAgSgTg");
	this.shape_2.setTransform(167.8,46.6,0.374,0.373);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AFHEcIAAl7QAAhbg3gmQghgXgtAAQhOAAguA0QgyA3AABhIAAFHIgoAAIAAl7QAAhag0gmQgggYguAAQhEAAgxAwQg7A5AABjIAAFHIgpAAIAAoqIApAAIAAByIACAAQANg2AxgkQAyglA+AAQBJAAAuAmQAlAfAKAxIACAAQAZg7AqgcQArgfBCAAQBPAAAtAuQAyAxAABeIAAF6g");
	this.shape_3.setTransform(227.2,38.5,0.374,0.373);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ai7DMQhDhRAAh7QAAh6BDhRQBGhWB1AAQB2AABGBWQBDBRAAB6QAAB7hDBRQhGBWh2AAQh1AAhGhWgAieiwQg3BHAABpQAABqA3BHQA7BNBjAAQBkAAA7hNQA3hHAAhqQAAhpg3hHQg7hOhkAAQhjAAg7BOg");
	this.shape_4.setTransform(201,38.8,0.374,0.373);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AghFaQg1gggBhOIAAlMIhdAAIAAhoIBdAAIAAiqICaAAIAACqIByAAIAABoIhyAAIAAEXQAAAnAOANQANANAnAAQAcAAAUgEIAAB5QggAGg7AAQhSAAgpgZg");
	this.shape_5.setTransform(155.6,35.5,0.374,0.373);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABuEiIAAk+QAAhHgXghQgYgjg1AAQg+AAgcAmQgdAmAABWIAAEnIibAAIAAo0ICTAAIAABPIAEAAQAcguAwgZQAsgXAzAAQB1AAAxBAQApA2AAByIAAFbg");
	this.shape_6.setTransform(138.3,38.3,0.374,0.373);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AjLDXQhOhSAAiEQAAiABQhUQBRhWB/AAQCJAABMBnQBGBegJCKImXAAQAHCPCDAAQAtAAAkgYQAigVAIgcICIAAQg+C+jKAAQiEAAhOhTgAhhiIQgbAhgCArID8AAQgLg9gcgcQgegfg3AAQhAAAgjAsg");
	this.shape_7.setTransform(116.3,38.6,0.374,0.373);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AClGGQgNgegFg6QgFhDgFggQgJg/gcgaQgdgdhAAAIiqAAIAAExIisAAIAAsLIGkAAQBmAABBA/QA9A9AABbQAACSh7AxIAAACQBnAbAKCbIAHBfQAHA+ATAcgAijgkIC7AAQA6AAAdgbQAfgbAAg6QAAhsh2AAIi7AAg");
	this.shape_8.setTransform(92.2,34.6,0.374,0.373);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai1EiIAAo0ICTAAIAABpIADAAQAUg1AzgiQAzghA5AAQASAAAQAFIAACQQgagFgeAAQhQAAgnA1QghAvAABQIAAD/g");
	this.shape_9.setTransform(71,38.3,0.374,0.373);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AjUDYQhQhRAAiGQAAiHBQhRQBQhSCEAAQCFAABQBSQBPBRAACHQAACGhPBRQhQBSiFAAQiEAAhQhSgAhrh7QgdAvAABNQAABNAdAuQAjA5BIAAQBJAAAjg5QAdguAAhNQAAhNgdgvQgjg5hJAAQhIAAgjA5g");
	this.shape_10.setTransform(51.4,38.6,0.374,0.373);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AkRGGIAAsLIIjAAIAACQIl3AAIAAC0IFFAAIAACFIlFAAIAAFCg");
	this.shape_11.setTransform(30.2,34.6,0.374,0.373);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// shape
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#C60889").s().p("A0TFZIAAqxMAonABGIAAJrg");
	this.shape_12.setTransform(130,34.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_logo, new cjs.Rectangle(0,0,260,69), null);


(lib.m_image = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.rainMan();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_image, new cjs.Rectangle(0,0,300,287), null);


(lib.drop = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.486,1],0.7,-24.9,0.7,25.8).s().dr(-0.5,-25,1,50);
	this.shape.setTransform(0.5,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.drop, new cjs.Rectangle(0,0,1,50), null);


(lib.m_dontsuffertext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgcBIQgHgDgFgHQgFgGgCgJQgCgKAAgLQAAgNACgKQADgJAGgHQAFgHAIgDQAIgEAJAAQAIAAAFADQAHACAGAGIAAgxIgPgCIAAgIIAiAAIAACLIANACIAAAIIgeAAIgCgQQgEAIgHAFIgIADIgLABQgJAAgHgDgAgQgOQgFADgCAGQgDAEgBAHQgCAIAAAJQABAUAEAIQACAGAEADQAFADAHABQAFAAAEgCQAEgDAEgDQADgEACgEQACgFAAgFIAAghQAAgFgCgEIgFgHQgDgDgEgBQgEgCgEAAQgHAAgFADg");
	this.shape.setTransform(188,11.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AARAxQgEgEgBgHQgEAGgIAEQgGAEgKAAIgKgBQgFgCgEgDQgEgDgCgFQgCgFAAgHQAAgIADgFQADgGAGgDQAFgEAIAAQAHgCAJAAIANAAIAAgNIgBgMQgBgFgCgDQgCgEgEgCQgDgBgFAAQgQAAAAAIIAAADIAGAAIACAHQAAAFgEADQgDACgFAAQgFAAgDgDQgDgDAAgGQAAgFADgFQACgFAFgDQAEgDAGgCQAHgCAHAAQAIAAAGACQAHACAEAFQAFAEACAHQACAHAAALIAAAtQAAAGABACQABADAEAAIAGgBIACAGQgGAEgJAAQgHAAgFgDgAgKAHQgEABgDADIgEAGIgBAIQAAAIADAEQADAEAIAAQAIAAAEgFIAFgGQACgDAAgFIAAgQIgLAAQgFAAgFABg");
	this.shape_1.setTransform(177.7,13.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKBJQgHgDgFgFIgIAKIgGAAIAAiMIgNgCIAAgIIAgAAIAABAQAEgHAHgEIAIgEIALgBQAJAAAHADQAGAEAFAFQAFAHACAJQADAKAAAMQAAAMgDAJQgDAJgFAHQgFAIgIAEQgJADgLAAQgIAAgIgCgAgCgNIgIAFQgEADgBAFQgCAFAAAGIAAAdQAAAGACAEQABAFAEADQADAEAFACIAIACQAHgBAEgCQAEgCADgGQACgFACgIIABgSIgBgQIgEgMQgCgGgFgCQgEgCgHgBQgFABgDABg");
	this.shape_2.setTransform(167,11.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AARAxQgEgEgBgHQgEAGgIAEQgGAEgKAAIgKgBQgFgCgEgDQgEgDgCgFQgCgFAAgHQAAgIADgFQADgGAGgDQAFgEAIAAQAHgCAJAAIANAAIAAgNIgBgMQgBgFgCgDQgCgEgEgCQgDgBgFAAQgQAAAAAIIAAADIAGAAIACAHQAAAFgEADQgDACgFAAQgFAAgDgDQgDgDAAgGQAAgFADgFQACgFAFgDQAEgDAGgCQAHgCAHAAQAIAAAGACQAHACAEAFQAFAEACAHQACAHAAALIAAAtQAAAGABACQABADAEAAIAGgBIACAGQgGAEgJAAQgHAAgFgDgAgKAHQgEABgDADIgEAGIgBAIQAAAIADAEQADAEAIAAQAIAAAEgFIAFgGQACgDAAgFIAAgQIgLAAQgFAAgFABg");
	this.shape_3.setTransform(153.3,13.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAlAzIAAgIIAMgCIAAg5IgBgKQgBgEgCgCQgDgEgJAAQgGAAgEACQgEACgEADQgDAEgBAFQgCAEAAAGIAAAzIANACIAAAIIgrAAIAAgIIAMgCIAAg6QAAgLgDgEQgEgEgJAAQgFAAgEABQgFACgDAEQgDADgCAFQgCAEAAAGIAAA0IANACIAAAIIgsAAIAAgIIAMgCIAAhPIgMgCIAAgIIAcAAIACARQAEgIAIgFIAJgEQAFgCAHAAIAKABIAHAEIAFAGIADAIQAEgIAIgFQAEgDAFgBQAFgCAGAAQAIAAAFACQAFACAEAEQADAEACAHQABAGAAAJIAAA5IANACIAAAIg");
	this.shape_4.setTransform(136.1,13.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAwQgIgDgGgHQgFgHgDgJQgCgKAAgLQAAgLACgKQAEgKAFgGQAHgHAIgEQAIgEAKAAQALAAAIAEQAJAEAFAGQAGAHACAKQACAJABALQAAALgDAKQgDAKgGAHQgGAHgJADQgIAEgKAAQgKAAgJgEgAgLgmQgFADgCAGQgDAGgBAHIgBAQQABAVAEAIQADAGAEAEQAFADAHAAQAGAAAFgDQAEgDADgGQADgGABgIIABgPIgBgPQgBgIgDgGQgDgGgEgEQgFgDgHAAQgHAAgEADg");
	this.shape_5.setTransform(122.4,13.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmAzIAAgIIAMgCIAAhPIgMgCIAAgIIAcAAIACAQQAFgIAFgFIAIgEIAJgBQAJAAAFAFQADACACAEQABADAAAFQAAAIgEAEQgDADgHAAQgGAAgDgDQgDgDAAgHIAGgCIAAgDQAAgFgGAAQgEAAgDADQgEACgCAEQgDAEgCAEQgCAFAAAEIAAA2IAUACIAAAIg");
	this.shape_6.setTransform(113.5,13.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglBNIAAgIIAPgBIAAhPIgPAAIAAgKIAPAAIAAgKQAAgKACgIQACgJAFgGQAEgGAIgDQAGgDAJAAQAGAAAEABQAEABAEADQADACABAEQACAEAAAEQAAAGgDAEQgDADgGAAQgDAAgEgBQgCgCgBgDIgBgGIAGgCIABgEQAAgDgDgCQgCgBgEAAQgGAAgDACQgEACAAAEQgDAGAAANIAAAUIAYAAIAAAKIgYAAIAABPIAVABIAAAIg");
	this.shape_7.setTransform(106.8,11.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgmAzIAAgIIAMgCIAAhPIgMgCIAAgIIAcAAIACAQQAFgIAFgFIAIgEIAJgBQAJAAAFAFQADACACAEQABADAAAFQAAAIgEAEQgDADgHAAQgGAAgDgDQgDgDAAgHIAGgCIAAgDQAAgFgGAAQgEAAgDADQgEACgCAEQgDAEgCAEQgCAFAAAEIAAA2IAUACIAAAIg");
	this.shape_8.setTransform(94.8,13.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgQAwQgIgDgGgHQgFgHgDgJQgCgJAAgMQAAgLADgKQADgKAGgHQAHgHAIgDQAIgEAJAAQAIAAAIADQAGACAFAGQAFAFADAIQACAJAAALIAAAHIg9AAQAAAJACAIQACAHADAFQADAGAFACQAFADAGAAQAKAAAGgEQAFgEAEgJIAJADQgCAGgDAEQgEAFgEAEQgFADgGACQgGACgHAAQgKAAgJgEgAgFgnQgFACgDAFQgDAEgBAGIgDAMIAqAAIAAgEIgBgMQgBgFgCgEQgDgDgDgCQgEgCgFAAQgEAAgEADg");
	this.shape_9.setTransform(85.6,13.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglBNIAAgIIAOgBIAAhPIgOAAIAAgKIAOAAIAAgKQABgKACgIQACgJAFgGQAEgGAIgDQAFgDAKAAQAFAAAFABQAEABADADQAEACACAEQABAEAAAEQAAAGgDAEQgDADgFAAQgFAAgDgBQgCgCgBgDIgBgGIAGgCIAAgEQABgDgDgCQgCgBgFAAQgFAAgEACQgCACgBAEQgEAGAAANIAAAUIAZAAIAAAKIgZAAIAABPIAXABIAAAIg");
	this.shape_10.setTransform(78.6,11.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AglBNIAAgIIAPgBIAAhPIgPAAIAAgKIAPAAIAAgKQAAgKACgIQACgJAFgGQAEgGAIgDQAGgDAJAAQAGAAAEABQAEABAEADQADACABAEQACAEAAAEQAAAGgDAEQgDADgGAAQgDAAgEgBQgCgCgBgDIgBgGIAGgCIABgEQAAgDgDgCQgCgBgEAAQgGAAgDACQgEACgBAEQgCAGAAANIAAAUIAYAAIAAAKIgYAAIAABPIAVABIAAAIg");
	this.shape_11.setTransform(72.2,11.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAxQgFgCgEgEQgEgEgBgHQgCgGAAgJIAAg5IgNgCIAAgIIAgAAIAABDQAAALADAEIAGAEQADACAFAAQAFAAAEgCQAFgCADgEQAEgDABgFQACgGAAgGIAAgyIgNgCIAAgIIAgAAIAABZIANACIAAAIIgdAAIgBgQQgFAIgIAEIgJAEQgEACgGAAQgIAAgGgCg");
	this.shape_12.setTransform(62.2,13.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIAzIgIgDQgGgEgCAAQgDAAAAAIIgHAAIAAgkIAIAAQAAAHADAFQACAEAFAEQAEADAFABQAEACAFAAQAJAAAFgEQAFgFAAgIQAAgFgCgEQgCgDgFgCQgDgCgOgDQgOgEgFgDQgEgDgCgEQgCgGAAgHQAAgGACgGQACgFAFgEQAEgEAGgDQAGgCAHAAQAHAAAHADIAHADQADAAAAgGIAHAAIAAAfIgIAAIgEgJIgFgHIgHgEIgHgBQgIAAgFADQgFAEAAAHQAAAEACADQACADAEACIASAFIAKADQAFACAEADQAEADACAFQACAFAAAIQAAAHgCAGQgCAGgEAEQgEAFgGACQgGADgIAAIgLgBg");
	this.shape_13.setTransform(52.5,13.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEBAQgEgBgDgDQgDgCgCgFQgCgFAAgGIAAhDIgOAAIAAgKIAOAAIAAgaIAPgDIADAAIAAAdIAWAAIAAAKIgWAAIAABAQAAAIACADQADAFAFAAQAHgBACgDQAEgDADgKIAHACIgEAMQgCAEgDADQgEAEgEABQgFACgGgBIgJgBg");
	this.shape_14.setTransform(41,12.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgDAYIgFgqQAGgFAEAAQADAAACACQACACAAADIgBAJIgFAfg");
	this.shape_15.setTransform(35.9,5.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAJAzIAAgIIANgCIAAg5QAAgKgEgFQgCgDgDgBIgJgBQgEAAgFABQgEACgEADQgDAEgCAEQgCAFAAAGIAAA0IANACIAAAIIgtAAIAAgIIANgCIAAhPIgNgCIAAgIIAcAAIACARQAEgIAIgFIAKgEQAFgCAGAAQAIAAAFACQAGACADAEQAEAEACAHQABAGAAAJIAAA5IANACIAAAIg");
	this.shape_16.setTransform(29.4,13.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTAwQgIgDgFgHQgGgHgDgJQgDgKAAgLQABgLADgKQACgKAHgGQAFgHAJgEQAJgEAIAAQAMAAAJAEQAHAEAGAGQAFAHADAKQACAJAAALQAAALgDAKQgCAKgGAHQgGAHgJADQgIAEgKAAQgKAAgJgEgAgLgmQgFADgDAGQgCAGgBAHIgBAQQABAVADAIQADAGAFAEQAFADAGAAQAIAAAEgDQAFgDADgGQACgGABgIIABgPIgBgPQgBgIgCgGQgDgGgFgEQgFgDgHAAQgHAAgEADg");
	this.shape_17.setTransform(18.4,13.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgcBIQgHgDgFgHQgFgGgCgJQgCgKAAgLQAAgNACgKQADgJAGgHQAFgHAIgDQAIgEAJAAQAIAAAFADQAHACAGAGIAAgxIgPgCIAAgIIAiAAIAACLIANACIAAAIIgeAAIgCgQQgEAIgHAFIgIADIgLABQgJAAgHgDgAgQgOQgFADgCAGQgDAEgBAHQgCAIAAAJQABAUAEAIQACAGAEADQAFADAHABQAFAAAEgCQAEgDAEgDQADgEACgEQACgFAAgFIAAghQAAgFgCgEIgFgHQgDgDgEgBQgEgCgEAAQgHAAgFADg");
	this.shape_18.setTransform(7.8,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_dontsuffertext, new cjs.Rectangle(0,0,210,26.4), null);


(lib.m_ctatext = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkBCxQgDgBgCgEQgBgEAAgEQAAgFADgEQADgEAGAAQAFAAACADQADAEABAGIgIADQAAAEACACQACABAEAAQAFAAADgGQADgFAHgTIghhYIgIgBIAAgIIApAAIAAAIIgNABIAWBAIAVhAIgMgBIAAgIIAgAAIAAAIIgJABIglBrIgGAKQgDAFgEACQgFACgGAAQgJAAgGgFgAG1CLQgDgDAAgGQAAgGADgEQAEgDAGAAQAGgBAEAEQAEADAAAHQAAAHgEADQgDAEgHAAQgHAAgDgFgAFoCMQgHgDgGgGQgFgHgCgIQgDgJAAgLQAAgMADgKQADgJAGgHQAGgGAIgDQAIgEAJABQAIgBAHADQAGADAFAFQAFAFACAHQACAIAAAKIAAAIIg6AAQAAAJABAIQABAHADAEQADAFAFADQAFACAHAAQAJAAAGgEQAFgDAEgIIAIACQgCAGgDAEQgDAFgEADQgFADgFADQgGABgHAAQgLAAgIgEgAFyA5IgHAGQgDAFgBAFIgCALIAoAAIAAgDIgBgMQgBgFgCgDQgCgDgEgCQgDgCgFAAQgFAAgEADgAgoCOQgFgCgEgEQgDgDgCgHQgCgGAAgIIAAg3IgMgCIAAgIIAeAAIAABBQAAAKAEAFQABACAEABQADABAFAAQAFAAAEgCQAEgBADgDQAEgEABgEQABgGAAgGIAAgwIgLgCIAAgIIAdAAIAABWIAMACIAAAHIgbAAIgBgPQgDAHgIAEQgEADgEACIgLABQgIAAgFgCgAiMCMQgIgDgFgHQgGgGgCgJQgDgJAAgLQAAgLADgJQADgKAGgGQAFgHAIgDQAIgEAKABQALgBAIAEQAIADAFAHQAFAGADAJQACAJAAALQAAALgDAKQgDAJgFAGQgGAHgIADQgIAEgKAAQgKAAgIgEgAiFA6QgEADgDAFQgCAFgBAIIgBAPQABAVADAHQADAHAEACQAFAEAHAAQAHAAAEgEQAEgDADgFIAEgMIAAgQIAAgPQgBgHgDgGQgDgGgEgDQgFgEgHABQgGgBgFAEgAqCCPIgLgDQgJgDgGgHQgGgGgDgKQgDgIAAgMQAAgLAEgJQADgJAGgHQAGgGAKgEQAGgDAQAAQAJgBAOAEIAIAFIAHAFQAGAHADAJQACAJAAALQAAALgDAJQgDAJgGAHQgGAHgKADQgNAEgJAAgAp8A7QgDACgCAFQgBAEgBAHIAAAiQABAHABAEQACAFADACQACACAFAAQAEAAACgCQADgCABgFQACgFABgXIgBgRQAAgHgCgEQgBgFgDgCQgCgCgFAAQgEAAgCACgAEQCOIAAgHIAOgCIAAhMIgPAAIAAgKIAPAAIAAgJQAAgJACgIQACgIAFgGQAEgFAHgCQAHgEAIAAQAGAAAEABQAEABADACQADACACAEQABADAAAEQAAAHgDADQgDAEgFAAQgEAAgCgCQgDgCgBgCIgBgHIAGgCIAAgDQAAgDgCgCQgCgBgEgBQgFABgEACQgDACgCAEQgCAGAAAMIAAASIAYAAIAAAKIgYAAIAABMIAWACIAAAHgADZCOIAAgHIANgCIAAhMIgNgCIAAgIIAfAAIAABWIAOACIAAAHgACiCOIAAgHIANgCIAAh7IgNgCIAAgHIAfAAIAACEIAOACIAAAHgAAsCOIAAgHIAMgCIAAhMIgMgCIAAgIIAbAAIABAQQAFgIAFgFIAIgDIAJgBQAIgBAFAFIAEAGQACADAAAEQAAAIgEADQgDAEgGAAQgGAAgDgEQgDgDAAgFIAGgDIAAgDQAAgEgGAAQgDAAgEACIgGAGQgDAEgCAEIgBAJIAAA0IATACIAAAHgAlkCOIAAgQIAHgBIAAgtQAAgJgCgDQgBgFgGABQgGgBgEAFQgCACAAAEIgBAJIAAAqIAHABIAAAQIg1AAIAAgQIALgBIAAg9IgMgCIAAgPIApAAIADARIAEgHIAFgHQAEgDAFgBQAGgBAHAAQAGAAAFABQAGABAEAEQADAEACAFQACAGAAAIIAAAzIAMABIAAAQgAniCOIgPgtIgBAAIgQAtIgZAAIgchPIgIgBIAAgPIAxAAIAAAPIgGABIAPAvIAMgkIgDgLIgIgBIAAgPIAwAAIAAAPIgIABIAPAvIAMgvIgKgBIAAgPIAlAAIAAAPIgJABIgYBPgADkAXQgCgCAAgGQAAgFACgDQADgDAGgBQAGABADACQADADAAAGQAAAFgDADQgDAEgGAAQgGAAgDgEgAjwgEQgDgCgCgDQgBgEAAgEQAAgGADgDQADgFAGAAQAFAAACAEQADADABAGIgIAEQAAAEACABQACABAEABQAFgBADgFQADgGAHgTIghhXIgIgBIAAgIIApAAIAAAIIgNABIAWBAIAVhAIgMgBIAAgIIAgAAIAAAIIgJABIglBrIgGAKQgDAFgEABQgFACgGAAQgJAAgGgEgAKRgqQgDgEAAgFQAAgGADgEQAEgEAGAAQAGAAAEAEQAEADAAAHQAAAGgEADQgDAEgHAAQgHABgDgFgAJEgpQgHgDgGgGQgFgHgCgJQgDgJAAgLQAAgMADgJQADgJAGgHQAGgGAIgDQAIgEAJAAQAIAAAHADQAGACAFAFQAFAFACAIQACAHAAALIAAAIIg6AAQAAAJABAHQABAHADAFQADAFAFADQAFACAHAAQAJAAAGgEQAFgDAEgJIAIADQgCAFgDAFQgDAEgEAEQgFADgFACQgGABgHAAQgLAAgIgDgAJOh9IgHAGQgDAFgBAGIgCALIAoAAIAAgEIgBgMQgBgFgCgDQgCgDgEgBQgDgCgFgBQgFAAgEADgAE8gpQgHgEgGgGQgFgGgDgKQgCgIAAgMQAAgLADgIQADgKAFgHQAGgGAIgDQAIgEAKAAQAKAAAIAEQAIADAFAGQAFAHADAJQADAJAAALQAAALgDAJQgDAKgGAGQgFAGgIAEQgIADgKAAQgLAAgIgDgAFDh7QgEADgCAFQgDAFgBAHIgBAQQABAUAEAIQACAGAFADQAFADAGAAQAHAAAFgDQAEgDADgGIADgMIABgQIgBgPQgBgHgCgFQgDgHgEgCQgFgEgHAAQgHAAgFAEgAgXgoQgFgCgEgDQgDgEgCgHQgCgGAAgHIAAg4IgMgBIAAgIIAeAAIAABBQAAAKAEAEQABACAEACQADABAFAAQAEAAAEgCQAEgCADgDQAEgDACgFQABgFAAgHIAAgwIgMgBIAAgIIAeAAIAABVIAMACIAAAHIgbAAIgBgPQgEAIgIAEQgEADgEABIgKABQgIAAgFgCgAh7gpQgIgEgFgGQgGgGgCgKQgDgIAAgMQAAgLADgIQADgKAGgHQAFgGAIgDQAIgEAKAAQALAAAIAEQAIADAFAGQAFAHADAJQACAJAAALQAAALgDAJQgDAKgFAGQgGAGgIAEQgIADgKAAQgKAAgIgDgAh0h7QgEADgDAFQgCAFgBAHIgBAQQABAUADAIQADAGAEADQAFADAHAAQAHAAAEgDQAEgDADgGIAEgMIAAgQIAAgPQgBgHgDgFQgDgHgEgCQgFgEgHAAQgGAAgFAEgAlQgnQgGgCgEgDQgFgFgCgFQgCgHAAgIIAAgxIgOAAIAAgRIAOAAIAAgXIAVgEIAOAAIAAAbIAbAAIAAARIgbAAIAAAzQAAAGACACQACADAEAAQAFAAADgEQACgDACgKIANAEIgEANQgDAGgDAFQgFADgFACQgGACgJAAQgIAAgGgBgAoogpQgJgDgGgGQgGgHgDgJQgEgJAAgLQAAgIAEgNQADgKAHgGQAGgIAJgDQAIgDALAAQAJAAAIADQAHACAGAFQAGAFADAIQADAJAAAKIAAALIg2AAQABAPADAFQACAEADACQAEACAFAAQAHAAAFgEQAEgEAEgJIAQAGQgDAHgDAGQgEAFgFAEQgGADgGACQgHACgHAAQgMAAgJgDgAobh7QgCACgBAFQgCAFAAAPIATAAIAAgEQAAgPgBgEQgCgGgGABQgDAAgCABgAH3goIAAgHIAMgCIAAg3IgBgKIgDgGQgDgDgJAAQgFgBgEADQgEACgDADQgDADgCAFQgBAEAAAGIAAAxIAMACIAAAHIgqAAIAAgHIAMgCIAAg4QAAgKgEgEQgDgEgIAAQgFAAgFABQgEACgDAEQgDADgBAEQgCAFAAAFIAAAyIAMACIAAAHIgqAAIAAgHIAMgCIAAhMIgMgBIAAgIIAbAAIABAQQAFgIAHgFIAIgDQAGgCAGAAIAJABQAEABADACIAGAGIADAIQAEgIAHgFIAIgDQAFgCAGAAQAHAAAFACQAFACAEAEQADAEABAGQACAGAAAIIAAA3IAMACIAAAHgADvgoIAAgHIAMgCIAAg3QAAgKgDgEQgCgCgEgCQgDgCgFABQgFAAgEABQgFACgDAEQgDADgCAFQgCAFAAAHIAAAvIAMACIAAAHIgrAAIAAgHIANgCIAAh7IgNgCIAAgHIAfAAIAAA+QAEgHAHgFQAEgDAFAAQAFgCAGAAQAHAAAFACQAFACAEAEQADAEACAGQACAGAAAIIAAA3IAMACIAAAHgAA9goIAAgHIAMgCIAAhMIgMgBIAAgIIAbAAIABAPQAFgIAFgEIAIgEIAJgBQAIAAAFAEIAEAGQACADAAAEQAAAIgEAEQgDADgGAAQgGAAgDgDQgDgDAAgGIAGgDIAAgCQAAgFgGABQgDAAgEACIgGAGQgDADgCAEIgBAJIAAA0IATACIAAAHgAmjgoIAAgQIAGgBIAAgtQAAgJgBgDQgCgEgFAAQgHAAgDAEQgCACgBAFIgBAJIAAApIAIABIAAAQIg2AAIAAgQIALgBIAAg9IgLgCIAAgPIApAAIACARIAEgHIAGgGQAEgDAFgBQAFgCAHAAQAHAAAFACQAFABAEADQAEAEACAGQACAGAAAIIAAAyIALABIAAAQgAqogoIAAgQIAMgBIAAg9IgMgCIAAgPIAsAAIABAPQAEgHAFgFIAIgDQAFgCAGAAQAFAAAEACQAEABADADQADAEACAEQACAFAAAGQAAAGgCADQgBAFgDACQgCADgEABQgEACgEAAQgFAAgEgCIgFgDQgEgFABgKIAIgCIAAgCQAAgFgFAAQgEABgDACQgDACgBAEQgCADgBAGIgBAsIAWABIAAAQg");
	this.shape.setTransform(68.1,18.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctatext, new cjs.Rectangle(0,0,136.2,36.4), null);


(lib.m_ctashadow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().dr(-98.5,-26.5,197,53);
	this.shape.setTransform(98.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctashadow, new cjs.Rectangle(0,0,197,53), null);


(lib.m_ctadarkbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFA117").s().dr(-14.5,-26.5,29,53);
	this.shape.setTransform(14.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctadarkbox, new cjs.Rectangle(0,0,29,53), null);


(lib.m_ctabase = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB62C").s().dr(-98.5,-26.5,197,53);
	this.shape.setTransform(98.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctabase, new cjs.Rectangle(0,0,197,53), null);


(lib.m_ctaarrow = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxiVIBjCVIhjCWg");
	this.shape.setTransform(5,15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctaarrow, new cjs.Rectangle(0,0,10,30), null);


(lib.m_container = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = getMCSymbolPrototype(lib.m_container, null, null);


(lib.m_RENTlationshiptext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB62C").s().p("AhgB6IAAgdIATgDIAAiwIgUgEIAAgbIBKAAIADAYQAGgNAMgGQAFgEAIgCQAKgDAKABQAQAAANAFQANAGAIALQAIALAEAQQAFAQAAAVQgBAVgEARQgFAQgIANQgJAMgOAGQgNAHgRAAQgQAAgKgFQgJgEgHgIIAAAyIAaADIAAAcgAgBhZQgGAEgCAFQgGALAAATIAAAtQAAAQAHAKQAGAKALAAQAHAAAFgEQAFgEACgIQAEgKABglIgBgZQgBgMgDgGQgCgIgFgFQgFgEgHAAQgHAAgDADg");
	this.shape.setTransform(270,34.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFB62C").s().p("Ag3B/IAAgcIAZgCIAAhuIgYgCIAAgcIBVAAIAACMIAZACIAAAcgAgWg9QgIgDgEgFQgHgJAAgOQAAgPAJgJQAEgFAHgDQAIgCAKAAQAHAAAGACQAHACAFAEQAEAFACAGQADAGAAAJQAAAHgCAGQgCAHgEAEQgFAFgHADQgHACgIAAQgLAAgHgDg");
	this.shape_1.setTransform(254.5,27.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFB62C").s().p("AAHB+IAAgdIANgBIAAhRQgBgPgCgFQgCgIgKAAQgLAAgGAIQgEAEgBAGQgCAHAAAKIAABKIAOABIAAAdIhgAAIAAgdIATgBIAAjAIgTgDIAAgbIBSAAIAABrQAIgNAKgHQAFgEAIgCQAIgDAKABQAMAAAJACQAKADAHAHQAGAGAEAKQADALAAAOIAABaIAVABIAAAdg");
	this.shape_2.setTransform(238.4,27.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFB62C").s().p("AgXBTIgQgGQgDAAgFAJIgXAAIAAg3IAZAAQAGAOALAJQAGAFAHACQAJACAIABQAOgBAFgDQAGgEAAgHQAAgFgEgEQgDgDgJgCIgggHQgZgHgJgJQgIgHgDgIQgFgLABgNQAAgOAEgMQAGgLAIgIQAJgIAMgEQANgFANABQANgBAMAGQALAFACAAQAEAAADgHIAWAAIAAA0IgZAAQgIgQgIgHQgKgHgOAAQgKAAgGADQgIAEABAHQAAAFADAEQAEADAIADIAhAIIASAGQAJAEAHAGQAIAHADAIQAFALAAANQAAAOgFANQgFALgJAHQgJAIgMADQgLAFgOAAQgQgBgOgGg");
	this.shape_3.setTransform(220.3,31.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFB62C").s().p("AAIBXIAAgdIAMgBIAAhQQAAgPgCgGQgDgIgKAAQgLAAgGAIQgDAEgCAHQgCAHAAAKIAABJIAOABIAAAdIhgAAIAAgdIAUgBIAAhtIgUgEIAAgbIBJAAIAFAgIAGgOQAFgGAGgFQAGgEAIgEQAKgCAMAAQAMAAAKACQAJADAHAHQAHAGADAKQAEALAAAPIAABZIAUABIAAAdg");
	this.shape_4.setTransform(202.1,31.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFB62C").s().p("AgWBXIgTgEQgQgHgLgLQgKgMgGgQQgEgQAAgUQAAgTAFgQQAGgRALgMQALgMASgGQAKgFAcgCQAQgBAZAIQAJADAGAEQAHAFAFAGQALALAEARQAGAPAAAUQgBATgFARQgGAQgLANQgLALgRAHQgZAGgOABgAgMg9QgEAEgCAHQgEAIgBAMIgBAeIABAeQABANAEAIQACAIAFAEQAEADAIgBQAHAAAEgDQAFgDADgJQADgKABgnIgBgeQgBgNgCgIQgDgIgFgDQgEgEgIAAQgGAAgGAEg");
	this.shape_5.setTransform(182.1,31.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFB62C").s().p("Ag3B/IAAgcIAZgCIAAhuIgYgCIAAgcIBVAAIAACMIAZACIAAAcgAgXg9QgGgDgFgFQgHgJAAgOQAAgPAIgJQAFgFAHgDQAIgCAKAAQAHAAAGACQAHACAEAEQAGAFABAGQADAGAAAJQAAAHgCAGQgCAHgEAEQgFAFgHADQgHACgJAAQgKAAgIgDg");
	this.shape_6.setTransform(167.5,27.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFB62C").s().p("AgOBsQgLgDgHgHQgIgHgEgKQgDgLAAgQIAAhWIgZAAIAAgeIAZAAIAAgqIAlgHIAYAAIAAAxIAxAAIAAAeIgxAAIAABaQAAALADAFQAEAGAIAAQAIAAAFgIQAEgGAEgSIAXAGQgDAPgEAKQgFALgHAHQgHAHgLAEQgKAEgPAAQgOAAgLgEg");
	this.shape_7.setTransform(154.8,29);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFB62C").s().p("AAXBTQgGgGgFgNQgFAMgJAGQgGAEgIABQgKADgLAAQgLAAgJgDQgIgDgHgFQgHgFgEgJQgEgJAAgMQAAgOAFgJQAEgJAIgGQAIgFANgBQAMgDASAAIAWAAIAAgYQAAgUgEgJQgDgGgFgBQgFgEgJAAQgHABgDACQgEACABAFIAAAFIANAAIACAOQAAAMgGAGQgIAIgPAAQgIAAgFgDQgGgBgDgFQgHgHAAgOQAAgKAEgIQAEgJAKgHQAJgFANgEQAOgEASABQAQgBANAEQAOADAKAHQAJAIAGAMQAEANAAASIAABBIABANQABAFAFgBQAFABAGgDIAFAUQgVAOgVAAQgQAAgHgHgAgVAVQgEAFAAANQAAALAEAGQAEAGAHAAQAHgBADgFQADgGAAgNIAAgVIgJAAQgLAAgEAFg");
	this.shape_8.setTransform(139.8,31.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFB62C").s().p("AgzB+IAAgcIAUgCIAAi/IgUgDIAAgcIBSAAIAADeIAWACIAAAcg");
	this.shape_9.setTransform(124.9,27.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFB62C").s().p("Ag/B3IAAggIAfgCIAAipQgLAAgIACQgHADgFAGQgFAFgDALIgGAaIgeAAIAEhXIDPAAIAEBXIgfAAIgGgbQgDgLgFgGQgEgFgIgCQgGgCgMAAIAACpIAfACIAAAgg");
	this.shape_10.setTransform(107.9,27.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFB62C").s().p("AAmB3IheirIgBAAIAACKIAVABIAAAgIhMAAIAAggIASgBIAAiqIgSgCIAAggIBhAAIBJCOIACAAIAAhsIgUgCIAAggIBKAAIAAAgIgSACIAADLg");
	this.shape_11.setTransform(84.9,27.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFB62C").s().p("AhiB3IAAgfIATgDIAAipIgTgCIAAggIC8AAIADBQIgeAAQgDgPgFgIQgFgKgHgEQgHgFgLgDQgKgBgPAAIgNAAIAABGIAEAAQANAAAHgIQAGgHAEgVIAYAAIAABjIgZAAIgEgTQgCgIgEgEQgGgGgPAAIgCAAIAABJIAMAAQASAAAMgCQANgEAIgGQAHgGAFgLQAEgKADgRIAeAAIgDBag");
	this.shape_12.setTransform(62.1,27.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFB62C").s().p("AAoB2QgKgDgHgGQgIgHgEgJQgFgLAAgOIAAgZQAAgRgGgIQgFgIgNAAIgLAAIAABJIASACIAAAgIhoAAIAAggIAVgCIAAipIgVgCIAAggIBYAAQAWAAAPACQATACAOAGQAQAHAIAKQAFAHACAHQACAIAAAJQAAAOgEAKQgEAKgIAHQgIAGgLAEQgLAEgPABIAAABQAPACALADQALAEAHAGQAHAHADALQADAJAAAQIAAASQAAAKACADQACAFAHABQAHAAADgJIAEgYIATADQAAAPgDALQgEALgGAIQgHAIgLAEQgKAEgQAAQgKAAgJgDgAgdgRIAEAAQAJAAAHgCQAHgCADgFQAEgEACgHQACgHAAgIQAAgKgCgHQgCgFgEgEQgHgIgRAAIgGAAg");
	this.shape_13.setTransform(40,28.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFB62C").s().p("AAQB3IAKg+IhDAAIgKA+IgZAAIAKg+Ig0AAIAFgXIAzAAIALhGIg1AAIAFgYIAzAAIAIg6IAaAAIgJA6IBBAAIAJg6IAYAAIgJA6IA1AAIgEAYIg0AAIgKBGIA0AAIgEAXIgzAAIgKA+gAglAiIBCAAIAKhGIhBAAg");
	this.shape_14.setTransform(15.1,27.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_RENTlationshiptext, new cjs.Rectangle(0,0,295,54.4), null);


(lib.m_imageclipped = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AB6VOIgKgFI2cAAQgCgvAHhUIAHhLQAdkNAoimIAjhxQALgvAcgrIAZgiQAJgMAOgQIAMgOQANgbAjgsIBchtQAEgGAHgJIAHgHQAIgBANgIQAig8AhgUIAbgHQAIgBALgHQAJggAKgYIAIgSIgIgJQgOACgNgQIgLgRQAKgNgFgLIgHgIIAAgrQgHgDgBgLIAAgJQAJgJgJgJQgDgcAFgVIAEgQQAAgfAEgRIAEgLQgBgOAFgNIAFgJQABgVAGgQIAFgMQAEgHAAgOQAoh4Blg4QAzgbAqgEQAbgIAvgBIAqABQAtgCAQAFIAKAFQAEgDAmAFQBBATA1AwQAbAYANAVQASALABAMQgBAPAUApQAYAZAGAcQADAOgCAJQgBAJAHAEQAEACADAAQAjAEAAAqQABAVgHAVQAYASADAJQgBAXgYAZIgZATQgDAsAJASQAFALgJAMIgKALQAMAJgFAMQgCAGgFAEQgDAOAFAKQACAFACACQAJA5glAbQgMAIgPAFIgMACQgJACgmAQIgkARQhCAWgjAdIgWAYQgIATgqAkQAJABgBAjIAVAlQADAEgBAjQAKAEALAqQAXAPAnA9QAFAMAIgCQASAPANACQAOgFASAFQAJACAHAEQALAMAhgGQANgOAPAFQAIADAEAGQAFAGAWgGQAHgMAJACQAEABADADQAIAOATgCQAEgKAIACQAEABAEADQAGACARACQAOgTAfAEQAQABANAGQAIgGAGADQADACACADQAIAIAegEQAOgCANgEQAMgUAUAFQAKADAIAGQAXgOAhAIQAJgIAIAAQApABAsgKQAIgKAWAGQAPgIAUguQADgQAMgeIAMgaQAAgTAGgKQADgFADgBQAFgOAdgKQAPgFAOgCQASgJBMgMQAEgKAKgEIANgGQAcgHCPAJQBSAUA9AZQAeANAOAIQATAICIApIB0hzQAxAxAFBDQADAhgHAYQgJAEguAIIgtAHIg+BKQAGAUgKARIgLANQAJAGAGATQAEAXgYATIgYAOQAIABANAHQARAZgXAoIgbAiQANAWgIAaQgEANgGAJQgFAPgQAFIgOADQAMARgIAJIgMAHQgIgBgOAFIgMAFQgTAggsALIgpAGIguAPQAGAtgEAfQgOAmgtAOIgrAIQgTAIgtAdIgqAbQgBAUgRADIgRgCQgIALgLgEIgJgHQgTgQgPAEIgLAIIgdAPIgJAFQgHANgKgIQgNAOgOACIgMAAQgGAJgIgCIgHgDQgNAJgyADIguABQgJgIgIAFQgEADgCAEIigAUQgIADgIAAQgGAAgFgCg");
	mask.setTransform(115.5,136);

	// image
	this.instance = new lib.m_image();
	this.instance.parent = this;
	this.instance.setTransform(150,143,1,1,0,0,0,150,143);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_imageclipped, new cjs.Rectangle(0,81,248,191.1), null);


(lib.m_imageanimation = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//this.stop();
	}
	this.frame_30 = function() {
		this.stop();
		this.parent.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(30).call(this.frame_30).wait(1));

	// image mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_15 = new cjs.Graphics().p("AguVoQgRgXABgfQgBgfARgWQAQgWAWAAQAWAAAPAWQAQAWAAAfQAAAfgQAXQgPAWgWAAQgWAAgQgWg");
	var mask_graphics_16 = new cjs.Graphics().p("AhwDlQgQgXAAgfQAAgfAViuQAVivBlgnQBlgnALDdQAKDdgzAlQgzAkgqAKQgsAJgWAAQgXAAgQgWg");
	var mask_graphics_17 = new cjs.Graphics().p("Ag7GsQhIgEgWAAQgXAAgQgWQgQgWAAgfQAAgfAalHQAalHC0hPQC1hOAEGlQAEGjhlAqQhfAnhDAAIgJAAg");
	var mask_graphics_18 = new cjs.Graphics().p("AhxWEQhjgRgXAAQgWAAgQgWQgQgWAAgfQAAgfAfnhQAfngEDh1QEEh2gCJsQgCJsiYAwQhyAjhSAAQgcAAgZgEg");
	var mask_graphics_19 = new cjs.Graphics().p("AkKLrQhjgRgWAAQgXAAgQgWQgQgXAAgfQAAgfA1p4QA1p5FYhjQFZhkBMMNQBMMLlRAWQjCAMhzAAQhTAAgqgGg");
	var mask_graphics_20 = new cjs.Graphics().p("ADEOFQoIgEhigPQhjgRgXAAQgWAAgQgWQgQgXAAgfQAAgfBLsRQBLsRGuhSQGshRCaOsQCZOooFAAIgEAAg");
	var mask_graphics_21 = new cjs.Graphics().p("ADhWcQrBgdhjgQQhjgQgXAAQgWAAgQgXQgQgWAAgfQAAgfBhuqQBiuqICg/QIBhADoRMQDhQwqYAAIgjgBg");
	var mask_graphics_22 = new cjs.Graphics().p("ACORIQrBgehigPQhjgRgXAAQgWAAgQgWQgQgXAAgfQAAgfBfu5QBgu6LghrQLhhrALSIQAKRrqgAAIgigBg");
	var mask_graphics_23 = new cjs.Graphics().p("AANRxQrBgehigPQhjgRgXAAQgWAAgQgWQgQgXAAgfQAAgfBdvIQBevKO/iWQPAiXjTTDQjNSmqnAAIgggBg");
	var mask_graphics_24 = new cjs.Graphics().p("AiHSbQrCgehigPQhjgRgXAAQgWAAgQgWQgQgXAAgfQAAgfBbvZQBcvYSejCQSejCmvT+QmmTgqrAAIgfAAg");
	var mask_graphics_25 = new cjs.Graphics().p("AAjSnQubg0hvgSQhwgSgXAAQgWAAgQgWQgQgWAAgfQAAgfBevaQBevYScjBQSdjCjJUWQjBTiteAAQgjAAgjgBg");
	var mask_graphics_26 = new cjs.Graphics().p("ACySyQx2hLh9gTQh8gTgXAAQgWAAgQgWQgQgXAAgfQAAgfBhvZQBhvaSZjAQSbjAAeUtQAdTmv+AAQg6AAg9gEg");
	var mask_graphics_27 = new cjs.Graphics().p("AEdS9Q1QhhiJgVQiKgUgWAAQgXAAgQgWQgQgXAAgfQAAgfBkvZQBkvbSYi/QSXi/EGVFQDzTpyPAAQhUAAhdgHg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(15).to({graphics:mask_graphics_15,x:-6.3,y:140.6}).wait(1).to({graphics:mask_graphics_16,x:0.2,y:256.1}).wait(1).to({graphics:mask_graphics_17,x:8.2,y:238.7}).wait(1).to({graphics:mask_graphics_18,x:16.3,y:141.6}).wait(1).to({graphics:mask_graphics_19,x:31.6,y:208.2}).wait(1).to({graphics:mask_graphics_20,x:47.2,y:194.7}).wait(1).to({graphics:mask_graphics_21,x:62.9,y:143.7}).wait(1).to({graphics:mask_graphics_22,x:71.1,y:177.8}).wait(1).to({graphics:mask_graphics_23,x:84,y:173.7}).wait(1).to({graphics:mask_graphics_24,x:98.9,y:169.5}).wait(1).to({graphics:mask_graphics_25,x:106.2,y:170.8}).wait(1).to({graphics:mask_graphics_26,x:116.4,y:172.3}).wait(1).to({graphics:mask_graphics_27,x:130.1,y:173.7}).wait(4));

	// image
	this.instance = new lib.m_imageclipped();
	this.instance.parent = this;
	this.instance.setTransform(141.5,142,1,1,0,0,0,141.5,143);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(15).to({_off:false},0).wait(16));

	// outline mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("AixCwQhIhIAAhoQAAhmBIhLQBKhIBnAAQBnAABJBIQBKBLAABmQAABohKBIQhJBKhnAAQhnAAhKhKg");
	var mask_1_graphics_1 = new cjs.Graphics().p("AmNEUQhIhIAAhoQAAhmBIhLQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhJQBJhJBoAAQBnAABJBJQBKBJAABoQAABnhKBIQhJBKhnAAQhoAAhJhKIgQgRQADAUAAAVQAABohJBIQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_2 = new cjs.Graphics().p("AmNEUQhIhIAAhoQAAhmBIhLQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhJQBJhJBoAAQBnAABJBJQBKBJAABoQAABnhKBIQhJBKhnAAQhoAAhJhKIgQgRQADAUAAAVQAABohJBIQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_3 = new cjs.Graphics().p("AngH2QhIhJAAhnQAAhoBIhKQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhJQBJhIBoAAIASAAQgPgLgOgOQhJhJAAhoQAAhnBJhKQBJhJBoAAQBoAABIBJQBKBKAABnQAABohKBJQhIBJhoAAIgSAAQAOALAOANQBKBJAABoQAABnhKBJQhJBKhnAAQhoAAhJhKIgPgRQADAUAAAVQAABnhKBJQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_4 = new cjs.Graphics().p("AokLUQhIhJAAhnQAAhoBIhKQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhKQBKhIBnAAIASAAQgPgLgOgOQhIhJAAhnQAAhnBIhKQBChBBagHIgUgSQhJhJAAhoQAAhnBJhKQBJhJBoAAQBoAABIBJQBKBKAABnQAABohKBJQhBBChaAHIATARQBKBKAABnQAABnhKBJQhIBJhoAAIgSAAQAOALAOANQBKBKAABoQAABnhKBJQhJBKhnAAQhnAAhKhKIgPgRQADAUAAAVQAABnhKBJQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_5 = new cjs.Graphics().p("AtDLUQhIhJAAhnQAAhoBIhKQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhKQBKhIBoAAIASAAQgPgLgOgOQhJhJAAhnQAAhnBJhKQBChBBagHIgUgSQhJhJAAhoQAAhnBJhKQBJhJBnAAQBoAABIBJQBABAAJBWQASgsAkglQBJhIBoAAQBoAABIBIQBKBKAABoQAABnhKBJQgcAdgiASQBbAGBBBCQBKBKAABnQAABnhKBJQhIBJhoAAQhoAAhJhJQhJhJAAhnQAAhnBJhKQAdgdAhgRQhagHhChCQg/g/gIhWQgTArglAlQhBBChaAHIATARQBKBKAABnQAABnhKBJQhIBJhnAAIgSAAQAOALAOANQBJBKAABoQAABnhJBJQhJBKhnAAQhoAAhKhKIgPgRQADAUAAAVQAABnhKBJQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_6 = new cjs.Graphics().p("AtDLUQhIhJAAhnQAAhoBIhKQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhKQBKhIBoAAIASAAQgPgLgOgOQhJhJAAhnQAAhnBJhKQBChBBagHIgUgSQhJhJAAhoQAAhnBJhKQBJhJBnAAQBoAABIBJQBABAAJBWQASgsAkglQBJhIBoAAQBoAABIBIQBKBKAABoQAABnhKBJQgcAdgiASQBbAGBBBCQBKBKAABnQAABnhKBJQhIBJhoAAQhoAAhJhJQhJhJAAhnQAAhnBJhKQAdgdAhgRQhagHhChCQg/g/gIhWQgTArglAlQhBBChaAHIATARQBKBKAABnQAABnhKBJQhIBJhnAAIgSAAQAOALAOANQBJBKAABoQAABnhJBJQhJBKhnAAQhoAAhKhKIgPgRQADAUAAAVQAABnhKBJQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_7 = new cjs.Graphics().p("AtDLUQhIhJAAhnQAAhoBIhKQBKhIBoAAQBnAABJBIIARATQgDgUAAgVQAAhoBIhKQBKhIBoAAIASAAQgPgLgOgOQhJhJAAhnQAAhnBJhKQBChBBagHIgUgSQhJhJAAhoQAAhnBJhKQBJhJBnAAQBoAABIBJQBABAAJBWQASgsAkglQBJhIBoAAQBoAABIBIQBKBKAABoQAABnhKBJQgcAdgiASQBbAGBBBCQBKBKAABnQAABnhKBJQgxAxg/AQQBGBJAABlQAABohKBJQhIBJhoAAQhoAAhJhJQhJhJAAhoQAAhnBJhKQAxgxBAgQQhGhIAAhlQAAhnBJhKQAdgdAhgRQhagHhChCQg/g/gIhWQgTArglAlQhBBChaAHIATARQBKBKAABnQAABnhKBJQhIBJhnAAIgSAAQAOALAOANQBJBKAABoQAABnhJBJQhJBKhnAAQhoAAhKhKIgPgRQADAUAAAVQAABnhKBJQhJBKhnAAQhoAAhKhKg");
	var mask_1_graphics_8 = new cjs.Graphics().p("AJ2LXQg6g6gMhNQhFBBhiAAQhoAAhJhJQhJhJAAhoQAAhnBJhKQAxgxBAgQQhGhIAAhlQAAhnBJhKQAcgdAigRQhbgHhChCQg+g/gJhWQgSArglAlQhBBChZAHIATARQBJBKAABnQAABohJBIQhJBJhnAAIgTAAQAPALAOANQBJBKABBoQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAVQAABnhJBJQhJBKhoAAQhnAAhKhKQhIhJgBhnQABhoBIhKQBKhIBnAAQBoAABJBIIARATQgEgUAAgVQABhoBIhKQBJhIBoAAIATAAQgPgLgOgOQhJhIAAhoQAAhnBJhKQBBhBBbgHIgVgSQhIhJAAhoQAAhnBIhKQBKhJBoAAQBmAABJBJQBABAAIBWQATgsAjglQBKhIBoAAQBnAABJBIQBKBKAABoQAABnhKBJQgdAdghASQBbAGBBBCQBKBKAABnQAABnhKBJQgxAxg/AQQA3A5ALBKQBHg/BiAAQBnAABIBIQBLBKgBBoQABBnhLBJQhIBKhnAAQhoAAhKhKg");
	var mask_1_graphics_9 = new cjs.Graphics().p("AC0LXQg6g6gMhNQhFBBhhAAQhoAAhJhJQhJhJAAhoQAAhnBJhKQAxgxBAgQQhGhIAAhlQAAhnBJhKQAcgdAigRQhbgHhChCQg+g/gJhWQgSArglAlQhBBChaAHIATARQBKBKAABnQAABohKBIQhJBJhnAAIgTAAQAPALAOANQBJBKABBoQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAVQAABnhJBJQhJBKhoAAQhnAAhKhKQhIhJgBhnQABhoBIhKQBKhIBnAAQBoAABJBIIARATQgEgUAAgVQABhoBIhKQBJhIBoAAIATAAQgPgLgOgOQhJhIAAhoQAAhnBJhKQBBhBBbgHIgVgSQhIhJAAhoQAAhnBIhKQBKhJBoAAQBnAABJBJQBABAAIBWQATgsAjglQBKhIBoAAQBmAABJBIQBKBKAABoQAABnhKBJQgdAdghASQBbAGBBBCQBKBKAABnQAABnhKBJQgxAxg/AQQA3A5ALBKQBHg/BiAAQBnAABIBIIARATQAMhPA6g8QBKhIBoAAQBnAABIBIQAkAkASAqQASgqAjgjQBKhJBoAAQBnAABIBJQBLBKgBBnQABBohLBJQhIBJhnAAQhoAAhKhJQgjgjgSgqQgSApgkAjQhIBKhnAAQhoAAhKhKIgQgQQgLBOg8A6QhIBKhnAAQhoAAhKhKg");
	var mask_1_graphics_10 = new cjs.Graphics().p("AQ4OIQhIhJAAhnQAAhoBIhKQAqgpA0gSQg0gSgqgqQgjgjgSgqQgSApgkAjQhIBKhnAAQhoAAhKhKIgQgQQgLBOg8A6QhIBKhnAAQhoAAhKhKQg6g6gMhNQhFBBhhAAQhoAAhJhJQhJhJAAhoQAAhnBJhKQAxgxBAgPQhGhIAAhmQAAhnBJhKQAcgdAigRQhbgHhChCQg+g/gJhWQgSArglAlQhBBChaAHIATARQBKBKAABnQAABohKBJQhJBJhnAAIgTAAQAPALAOANQBJBJABBoQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAVQAABnhJBJQhJBKhoAAQhnAAhKhKQhIhJgBhnQABhoBIhKQBKhIBnAAQBoAABJBIIARATQgEgUAAgVQABhoBIhJQBJhIBoAAIATAAQgPgLgOgOQhJhJAAhoQAAhnBJhKQBBhBBbgHIgVgSQhIhJAAhoQAAhnBIhKQBKhJBoAAQBnAABJBJQBABAAIBWQATgsAjglQBKhIBoAAQBmAABJBIQBKBKAABoQAABnhKBJQgdAdghASQBbAGBBBCQBKBKAABnQAABohKBJQgxAwg/AQQA3A5ALBKQBHg/BiAAQBnAABIBIIARATQAMhPA6g8QBKhIBoAAQBnAABIBIQAkAkASAqQASgqAjgjQBKhJBoAAQBnAABIBJQBLBKgBBnQABBohLBJQgpAqg0ASQA0ASApApQBLBKgBBoQABBnhLBJQhIBKhnAAQhoAAhKhKg");
	var mask_1_graphics_11 = new cjs.Graphics().p("AQ4OIQhIhJAAhnQAAhoBIhKQAqgpA0gSQg0gSgqgqQgjgjgSgqQgSApgkAjQhIBKhnAAQhoAAhKhKIgQgQQgLBOg8A6QhIBKhnAAQhoAAhKhKQg6g6gMhNQhFBBhhAAQhoAAhJhJQhJhJAAhoQAAhnBJhKQAxgxBAgPQhGhIAAhmQAAhnBJhKQAcgdAigRQhbgHhChCQg+g/gJhWQgSArglAlQhBBChaAHIATARQBKBKAABnQAABohKBJQhJBJhnAAIgTAAQAPALAOANQBJBJABBoQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAVQAABnhJBJQhJBKhoAAQhnAAhKhKQhIhJgBhnQABhoBIhKQBKhIBnAAQBoAABJBIIARATQgEgUAAgVQABhoBIhJQBJhIBoAAIATAAQgPgLgOgOQhJhJAAhoQAAhnBJhKQBBhBBbgHIgVgSQhIhJAAhoQAAhnBIhKQBKhJBoAAQBnAABJBJQBABAAIBWQATgsAjglQBKhIBoAAQBmAABJBIQBKBKAABoQAABnhKBJQgdAdghASQBbAGBBBCQBKBKAABnQAABohKBJQgxAwg/AQQA3A5ALBKQBHg/BiAAQBnAABIBIIARATQAMhPA6g8QBKhIBoAAQBnAABIBIQAkAkASAqQASgqAjgjQBKhJBoAAQBnAABIBJQBLBKgBBnQABBohLBJQgpAqg0ASQA0ASApApQBLBKgBBoQABBnhLBJQhIBKhnAAQhoAAhKhKg");
	var mask_1_graphics_12 = new cjs.Graphics().p("ALQQNQhIhJAAhoQAAhnBIhKQBKhJBoAAQA+AAAyAaQgCgUAAgVQAAhnBIhKQAqgqA0gRQg0gTgqgqQgjgjgSgqQgSAqgkAjQhIBJhnAAQhoAAhKhJIgQgRQgLBOg8A7QhIBJhnAAQhoAAhKhJQg6g6gMhOQhFBChhAAQhoAAhJhKQhJhJAAhnQAAhnBJhKQAxgxBAgPQhGhJAAhlQAAhoBJhKQAcgcAigRQhbgHhChCQg+hAgJhWQgSAsglAkQhBBChaAHIATARQBKBKAABoQAABnhKBJQhJBKhnAAIgTgBQAPALAOAOQBJBKABBmQgBBohJBJQhJBJhoAAQhoAAhJhJIgPgRQACATAAAVQAABohJBJQhJBJhoAAQhnAAhKhJQhIhJgBhoQABhnBIhKQBKhIBnAAQBoAABJBIIARASQgEgUAAgVQABhmBIhKQBJhJBoAAIATABQgPgMgOgOQhJhJAAhnQAAhoBJhKQBBhBBbgHIgVgSQhIhJAAhnQAAhoBIhKQBKhIBoAAQBnAABJBIQBABAAIBWQATgsAjgkQBKhJBoAAQBmAABJBJQBKBKAABnQAABohKBJQgdAdghASQBbAGBBBBQBKBKAABoQAABnhKBJQgxAyg/AQQA3A5ALBJQBHg/BiAAQBnAABIBIIARASQAMhPA6g6QBKhJBoAAQBnAABIBJQAkAjASApQASgpAjgjQBKhIBoAAQBnAABIBIQBLBJgBBoQABBnhLBJQgpAqg0ATQA0ARApAqQBLBKgBBnQABBohLBJQhIBJhnAAQg+AAg0gaQADAUAAAVQABBohLBJQhIBJhnAAQhoAAhKhJg");
	var mask_1_graphics_13 = new cjs.Graphics().p("AD8Q5QhIhIAAhoQAAhnBIhLQBKhIBoAAQBnAABIBIQAbAbARAeQAKhTA9g/QBKhJBoAAQA+AAAyAbQgCgUAAgWQAAhnBIhKQAqgqA0gRQg0gSgqgrQgjgigSgqQgSApgkAjQhIBJhnAAQhoAAhKhJIgQgRQgLBOg8A7QhIBKhnAAQhoAAhKhKQg6g6gMhNQhFBBhhAAQhoAAhJhJQhJhKAAhnQAAhmBJhLQAxgwBAgQQhGhJAAhlQAAhnBJhLQAcgcAigRQhbgHhChCQg+g/gJhXQgSAsglAkQhBBChaAHIATARQBKBLAABnQAABnhKBKQhJBJhnAAIgTAAQAPAKAOAOQBJBKABBnQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAUQAABohJBJQhJBKhogBQhnABhKhKQhIhJgBhoQABhnBIhKQBKhHBnAAQBoAABJBHIARATQgEgUAAgVQABhnBIhKQBJhIBogBIATABQgPgLgOgOQhJhKAAhnQAAhnBJhLQBBhABbgHIgVgTQhIhIAAhoQAAhoBIhJQBKhJBoAAQBnAABJBJQBAA/AIBWQATgrAjglQBKhIBoAAQBmAABJBIQBKBKAABnQAABohKBJQgdAdghASQBbAGBBBBQBKBLAABnQAABohKBIQgxAyg/AQQA3A5ALBJQBHg/BiAAQBnAABIBIIARASQAMhNA6g8QBKhIBoAAQBnAABIBIQAkAjASArQASgqAjgjQBKhJBoAAQBnAABIBJQBLBKgBBmQABBohLBIQgpArg0ASQA0ARApAqQBLBKgBBnQABBohLBJQhIBKhngBQg+AAg0gaQADAUAAAWQABBnhLBJQhIBJhnABQhogBhKhJQgagagQgeQgKBUg/A9QhIBKhnAAQhoAAhKhKg");
	var mask_1_graphics_14 = new cjs.Graphics().p("AD8Q5QgpgpgSgzQgSAzgpApQhJBJhnAAQhnAAhKhJQgogogSgxQgSAxgoAoQhJBJhoAAQhoAAhJhJQhJhJAAhnQAAhoBJhKQBJhIBoAAQBoAABJBIQAoApASAxQASgxAogpQBKhIBnAAQBnAABJBIQApAqASAzQASgzApgqQBKhIBoAAQBnAABIBIQAbAbARAeQAKhTA9g/QBKhJBoAAQA+AAAyAbQgCgUAAgWQAAhnBIhKQAqgqA0gRQg0gSgqgrQgjgigSgqQgSApgkAjQhIBJhnAAQhoAAhKhJIgQgRQgLBOg8A7QhIBKhnAAQhoAAhKhKQg6g6gMhNQhFBBhhAAQhoAAhJhJQhJhKAAhnQAAhmBJhLQAxgwBAgQQhGhJAAhlQAAhnBJhLQAcgcAigRQhbgHhChCQg+g/gJhXQgSAsglAkQhBBChaAHIATARQBKBLAABnQAABnhKBKQhJBJhnAAIgTAAQAPAKAOAOQBJBKABBnQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAUQAABohJBJQhJBKhogBQhnABhKhKQhIhJgBhoQABhnBIhKQBKhHBnAAQBoAABJBHIARATQgEgUAAgVQABhnBIhKQBJhIBogBIATABQgPgLgOgOQhJhKAAhnQAAhnBJhLQBBhABbgHIgVgTQhIhIAAhoQAAhoBIhJQBKhJBoAAQBnAABJBJQBAA/AIBWQATgrAjglQBKhIBoAAQBmAABJBIQBKBKAABnQAABohKBJQgdAdghASQBbAGBBBBQBKBLAABnQAABohKBIQgxAyg/AQQA3A5ALBJQBHg/BiAAQBnAABIBIIARASQAMhNA6g8QBKhIBoAAQBnAABIBIQAkAjASArQASgqAjgjQBKhJBoAAQBnAABIBJQBLBKgBBmQABBohLBIQgpArg0ASQA0ARApAqQBLBKgBBnQABBohLBJQhIBKhngBQg+AAg0gaQADAUAAAWQABBnhLBJQhIBJhnABQhogBhKhJQgagagQgeQgKBUg/A9QhIBKhnAAQhoAAhKhKg");
	var mask_1_graphics_15 = new cjs.Graphics().p("AD8Q5QgpgpgSgzQgSAzgpApQhJBJhnAAQhnAAhKhJQgogogSgxQgSAxgoAoQhJBJhoAAQhoAAhJhJQgegegSgkQgSAkgeAeQhJBJhoAAQhoAAhJhJQhJhJAAhnQAAhoBJhKQBJhIBoAAQBoAABJBIQAeAfASAkQASgkAegfQBJhIBoAAQBoAABJBIQAoApASAxQASgxAogpQBKhIBnAAQBnAABJBIQApAqASAzQASgzApgqQBKhIBoAAQBnAABIBIQAbAbARAeQAKhTA9g/QBKhJBoAAQA+AAAyAbQgCgUAAgWQAAhnBIhKQAqgqA0gRQg0gSgqgrQgjgigSgqQgSApgkAjQhIBJhnAAQhoAAhKhJIgQgRQgLBOg8A7QhIBKhnAAQhoAAhKhKQg6g6gMhNQhFBBhhAAQhoAAhJhJQhJhKAAhnQAAhmBJhLQAxgwBAgQQhGhJAAhlQAAhnBJhLQAcgcAigRQhbgHhChCQg+g/gJhXQgSAsglAkQhBBChaAHIATARQBKBLAABnQAABnhKBKQhJBJhnAAIgTAAQAPAKAOAOQBJBKABBnQgBBnhJBJQhJBKhoAAQhoAAhJhKIgPgRQACAUAAAUQAABohJBJQhJBKhogBQhnABhKhKQhIhJgBhoQABhnBIhKQBKhHBnAAQBoAABJBHIARATQgEgUAAgVQABhnBIhKQBJhIBogBIATABQgPgLgOgOQhJhKAAhnQAAhnBJhLQBBhABbgHIgVgTQhIhIAAhoQAAhoBIhJQBKhJBoAAQBnAABJBJQBAA/AIBWQATgrAjglQBKhIBoAAQBmAABJBIQBKBKAABnQAABohKBJQgdAdghASQBbAGBBBBQBKBLAABnQAABohKBIQgxAyg/AQQA3A5ALBJQBHg/BiAAQBnAABIBIIARASQAMhNA6g8QBKhIBoAAQBnAABIBIQAkAjASArQASgqAjgjQBKhJBoAAQBnAABIBJQBLBKgBBmQABBohLBIQgpArg0ASQA0ARApAqQBLBKgBBnQABBohLBJQhIBKhngBQg+AAg0gaQADAUAAAWQABBnhLBJQhIBJhnABQhogBhKhJQgagagQgeQgKBUg/A9QhIBKhnAAQhoAAhKhKg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:-25,y:192.9}).wait(1).to({graphics:mask_1_graphics_1,x:-3,y:182.9}).wait(1).to({graphics:mask_1_graphics_2,x:-3,y:182.9}).wait(1).to({graphics:mask_1_graphics_3,x:5.3,y:160.3}).wait(1).to({graphics:mask_1_graphics_4,x:12.1,y:138.1}).wait(1).to({graphics:mask_1_graphics_5,x:40.8,y:138.1}).wait(1).to({graphics:mask_1_graphics_6,x:40.8,y:138.1}).wait(1).to({graphics:mask_1_graphics_7,x:40.8,y:138.1}).wait(1).to({graphics:mask_1_graphics_8,x:55.8,y:138.4}).wait(1).to({graphics:mask_1_graphics_9,x:100.8,y:138.4}).wait(1).to({graphics:mask_1_graphics_10,x:100.8,y:156.1}).wait(1).to({graphics:mask_1_graphics_11,x:100.8,y:156.1}).wait(1).to({graphics:mask_1_graphics_12,x:100.8,y:169.4}).wait(1).to({graphics:mask_1_graphics_13,x:100.8,y:173.9}).wait(1).to({graphics:mask_1_graphics_14,x:100.8,y:173.9}).wait(1).to({graphics:mask_1_graphics_15,x:100.8,y:173.9}).wait(16));

	// outline
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AlYuvQgmgFgEADQgCgCgIgDQgQgFgtACQgTgBgXAAQgvABgbAIQgqAEgzAbQhlA4goB4QAAAOgEAHIgFAMQgGAQgBAVIgFAJQgFANABAOIgEALQgEARAAAfIgEAQQgFAVADAcQAJAJgJAJIAAAJQABALAHADIAAArIAHAIQAFAMgKANIALARQANAQAOgCIAIAJIgIASQgKAYgJAgQgLAHgIABIgbAHQghAUgiA8QgNAIgIABIgHAHQgHAJgEAGIhcBtQgjArgNAbIgMAOQgOAQgJAMIgZAiQgcArgLAvIgjBxQgoCmgdENIgHBLQgHBUACAvIWcAAIAKAFQAMAFAPgGICggUQACgEAEgDQAIgFAJAIIAugBQAygDANgJIAHADQAIACAGgJIAMAAQAOgCANgOQAKAIAHgNQADgCAGgDQAMgHARgIIALgIQAPgEATAQIAJAHQALAEAIgLIARACQARgDABgUIAqgbQAtgdATgIIArgIQAtgOAOgmQAEgfgGgtIAugPIApgGQAsgLATggIAMgFQAOgFAIABIAMgHQAIgJgMgRIAOgDQAQgFAFgPQAGgJAEgNQAIgagNgWIAbgiQAXgogRgZQgNgHgIgBIAYgOQAYgTgEgXQgGgTgJgGIALgNQAKgRgGgUIA+hKIAtgHQAugIAJgEQAHgYgDghQgFhCgxgxIh0ByQiIgpgTgIQgOgIgegMQg9gZhSgUQiPgJgcAHQgHADgGADQgKAEgEAKQhMAMgSAJQgOACgPAFQgdAJgFAOQgDABgDAFQgGAKAAATIgMAaQgMAegDAQQgUAugPAIQgWgGgIAKQgsAKgpgBQgIAAgJAIQghgIgXAOQgIgGgKgDQgUgFgMAUQgNAEgOACQgeAEgIgIQgCgDgDgCQgGgDgIAGQgNgGgQgBQgfgEgOATQgRgCgGgCQgEgDgEgBQgIgCgEAKQgTACgIgOQgDgDgEgBQgJgCgHAMQgWAGgFgGQgEgGgIgDQgPgFgNAOQghAGgLgMQgHgEgJgCQgSgFgOAFQgNgCgSgPQgIACgFgMQgng9gXgPQgLgqgKgEQABgjgDgEIgVgkQABgjgJgBQAqgkAIgTIAWgYQAjgdBCgWIAkgRQAmgQAJgCIAMgCQAPgFAMgIQAlgbgJg5QgCgCgCgFQgFgKADgOQAFgEACgGQAFgMgMgJIAKgLQAJgNgFgLQgJgSADgsIAZgTQAYgZABgXQgDgJgYgSQAHgVgBgVQAAgqgjgEQgDAAgEgCQgHgEABgJQACgJgDgOQgGgcgYgZQgUgpABgPQgBgMgSgLQgNgVgbgYQg1gwhBgTg");
	this.shape.setTransform(115.5,176.5);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},28).wait(3));

	// image
	this.instance_1 = new lib.m_image();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,142,1,1,0,0,0,150,143);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(27).to({_off:false},0).to({alpha:1},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,167.9,18,50);


(lib.m_dontsuffer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.instance = new lib.m_dontsuffertext();
	this.instance.parent = this;
	this.instance.setTransform(105,13.2,1,1,0,0,0,105,13.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shadow
	this.instance_1 = new lib.m_dontsuffertext();
	this.instance_1.parent = this;
	this.instance_1.setTransform(106.8,15.4,1,1,0,0,0,105,13.2);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 210, 7, 140, 0)];
	this.instance_1.cache(-2,-2,214,30);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_dontsuffer, new cjs.Rectangle(0,0,211.8,28.6), null);


(lib.m_cta = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// text
	this.m_text = new lib.m_ctatext();
	this.m_text.parent = this;
	this.m_text.setTransform(12,27.2,1,1,0,0,0,0,18.2);

	this.timeline.addTween(cjs.Tween.get(this.m_text).wait(1));

	// arrow
	this.m_arrow = new lib.m_ctaarrow();
	this.m_arrow.parent = this;
	this.m_arrow.setTransform(182.5,26.5,1,1,0,0,0,5,15);

	this.timeline.addTween(cjs.Tween.get(this.m_arrow).wait(1));

	// dark
	this.m_dark = new lib.m_ctadarkbox();
	this.m_dark.parent = this;
	this.m_dark.setTransform(197,26.5,1,1,0,0,0,29,26.5);

	this.timeline.addTween(cjs.Tween.get(this.m_dark).wait(1));

	// base
	this.instance = new lib.m_ctabase();
	this.instance.parent = this;
	this.instance.setTransform(98.5,26.5,1,1,0,0,0,98.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shadow
	this.instance_1 = new lib.m_ctashadow();
	this.instance_1.parent = this;
	this.instance_1.setTransform(103.5,31.5,1,1,0,0,0,98.5,26.5);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_cta, new cjs.Rectangle(0,0,202,58), null);


(lib.m_RENTlationship = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text
	this.instance = new lib.m_RENTlationshiptext();
	this.instance.parent = this;
	this.instance.setTransform(147.5,27.2,1,1,0,0,0,147.5,27.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// text shadow
	this.instance_1 = new lib.m_RENTlationshiptext();
	this.instance_1.parent = this;
	this.instance_1.setTransform(151.3,31.4,1,1,0,0,0,147.5,27.2);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 210, 7, 140, 0)];
	this.instance_1.cache(-2,-2,299,58);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_RENTlationship, new cjs.Rectangle(0,0,298.8,58.6), null);


// stage content:
(lib.ForRent_RainMan_300x600 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var root = this,
			cta = root.m_cta,
			text = cta.m_text,
			dark = cta.m_dark,
			arrow = cta.m_arrow,
			time = .35,
			numDrops = 300,
			container = root.container,
			speed = 40,
			drops = [];
		
		root.stop();
		
		cta.addEventListener("mouseover", handleCTAOver);
		cta.addEventListener("mouseout", handleCTAOut);
		
		function handleCTAOver() {
			TweenMax.to(text, time, {scaleX:.8, scaleY:.75, ease:Back.easeOut});
			TweenMax.to(dark, time, {scaleX:2.25, ease:Back.easeOut});
			TweenMax.to(arrow, time, {x:167, ease:Back.easeOut});
		}
		
		function handleCTAOut() {
			TweenMax.to(text, time, {scaleX:1, scaleY:1, ease:Back.easeOut});
			TweenMax.to(dark, time, {scaleX:1, ease:Back.easeOut});
			TweenMax.to(arrow, time, {x:183, ease:Back.easeOut});
		}
		
		function randRange( minNum, maxNum) {
		  return ((Math.random() * (maxNum - minNum)) + minNum);
		}
		
		function createRain() {
		
			TweenMax.set(container, {rotation:-10});
			
			for (var i = 0; i < numDrops; i++) {
				var drop = new lib.drop();
				setDrop(drop);
				container.addChild(drop);
				drops.push(drop);
			}
			
			createjs.Ticker.addEventListener("tick", makeItRain);
		}
		
		function makeItRain() {
			for (var i = 0; i < drops.length; i++) {
				var drop = drops[i];
				drop.y += speed;
				if (drop.y > stage.canvas.height) {
					setDrop(drop);
				}
			}
		}
		
		function setDrop(drop) {
			drop.alpha = randRange(.2, .8);
			drop.x = randRange(-50, 350);
			drop.y = randRange(-250, -1000), 
			drop.height =randRange(5, 60);
		}
		
		
		setTimeout(function(){ 
			createRain(); 
		}, 1000);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(71));

	// cta
	this.m_cta = new lib.m_cta();
	this.m_cta.parent = this;
	this.m_cta.setTransform(309,382.1,1,1,-2,0,0,0.1,29);

	this.timeline.addTween(cjs.Tween.get(this.m_cta).wait(57).to({regX:99.2,regY:33.5,scaleX:0,scaleY:0.01,rotation:0,skewX:-1.7,skewY:-1.8,x:149.8,y:378.8},0).to({regX:101,regY:29.2,scaleX:1.1,scaleY:1.1,rotation:-1.8,skewX:0,skewY:0,x:149.9,y:378.7},7,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-2,y:378.8},6,cjs.Ease.get(1)).wait(1));

	// don't suffer
	this.instance = new lib.m_dontsuffer();
	this.instance.parent = this;
	this.instance.setTransform(-7.8,53.4,1,1,-140,0,0,0,13.2);
	this.instance.shadow = new cjs.Shadow("rgba(210,7,140,1)",-2,2,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.2,regY:13.3,rotation:1,x:32,y:53.2},5,cjs.Ease.get(1)).to({regX:0.1,regY:13.2,rotation:-5,x:32.1},4,cjs.Ease.get(1)).wait(17).to({y:49.2},2).wait(1).to({y:53.2},0).wait(42));

	// #RENTlationship
	this.instance_1 = new lib.m_RENTlationship();
	this.instance_1.parent = this;
	this.instance_1.setTransform(155.5,70.9,4.199,4.199,-2.8,0,0,147.6,27.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(23).to({_off:false},0).to({regX:147.7,scaleX:1,scaleY:1,rotation:-3,y:70.8},3,cjs.Ease.get(-1)).to({regX:147.6,scaleX:1.15,scaleY:1.15,rotation:-2.8,x:155.4,y:70.9},2).to({scaleX:1,scaleY:1,rotation:-3,y:70.8},2).wait(41));

	// subhead
	this.instance_2 = new lib.m_subhead();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-260.6,464,1,1,-1,0,0,0.1,21.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(45).to({_off:false},0).to({rotation:3,x:29.4},5,cjs.Ease.get(-1)).to({regY:20.9,rotation:2,x:19.4,y:463.9},3,cjs.Ease.get(1)).wait(18));

	// subhead shape
	this.instance_3 = new lib.m_subheadshape();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-280,469.4,1,1,0,0,0,0,37.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(40).to({_off:false},0).to({x:20},5,cjs.Ease.get(-1)).to({x:0},3,cjs.Ease.get(1)).wait(23));

	// logo
	this.instance_4 = new lib.m_logo();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,565.5,1,1,0,0,0,130,34.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(71));

	// png mask
	this.instance_5 = new lib._300x600_mask();
	this.instance_5.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(71));

	// rain container
	this.container = new lib.m_container();
	this.container.parent = this;
	this.container.setTransform(0,116);

	this.timeline.addTween(cjs.Tween.get(this.container).wait(71));

	// image
	this.instance_6 = new lib.m_imageanimation();
	this.instance_6.parent = this;
	this.instance_6.setTransform(141.5,259,1,1,0,0,0,141.5,143);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(71));

	// background
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C30786").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(71));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.2,205.5,699,694.6);
// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"_300x600_mask.png?1481301461938", id:"_300x600_mask"},
		{src:"rainMan.jpg?1481301461938", id:"rainMan"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;